package httpapi

import (
	"context"
	"net/http"

	"github.com/danielgtaylor/huma/v2"
	"github.com/google/uuid"

	"github.com/hamid-karimi/coachin/apps/api/internal/app/training"
)

// ProgramService is the program-manager use cases.
type ProgramService interface {
	List(ctx context.Context, userID uuid.UUID) ([]training.Program, error)
	Archive(ctx context.Context, userID, planID uuid.UUID) error
	CalendarExport(ctx context.Context, userID uuid.UUID) (string, error)
}

// ProgramBody is one active plan on the programs page.
type ProgramBody struct {
	ID             uuid.UUID `json:"id"`
	PlanKind       string    `json:"planKind" enum:"race,hypertrophy"`
	RaceTarget     *string   `json:"raceTarget" doc:"Running plans: base, 5k, 10k, half, full, ultra, other"`
	RaceDistanceKm *float64  `json:"raceDistanceKm"`
	RaceDate       *string   `json:"raceDate" format:"date"`
	GoalTime       *string   `json:"goalTime"`
	WeeksTotal     int       `json:"weeksTotal"`
	CurrentWeek    int       `json:"currentWeek"`
	DaysUntilRace  *int      `json:"daysUntilRace"`
	FromCoach      bool      `json:"fromCoach" doc:"Generated by the trainee's coach"`
	ReviewWeek     int       `json:"reviewWeek" doc:"Last fully elapsed week; 0 during week 1"`
	CheckinDue     bool      `json:"checkinDue"`
}

type programsOutput struct {
	Body []ProgramBody
}

type calendarOutput struct {
	ContentType        string `header:"Content-Type"`
	ContentDisposition string `header:"Content-Disposition"`
	Body               []byte
}

func registerTraining(api huma.API, deps Deps) {
	svc, logger := deps.Programs, deps.logger()
	signedIn := huma.Middlewares{requireUser(api)}
	tags := []string{"training"}

	huma.Register(api, huma.Operation{
		OperationID: "listPrograms", Method: http.MethodGet, Path: "/training/programs",
		Summary: "Active training plans with week, race countdown, and check-in state",
		Tags:    tags, Middlewares: signedIn, Errors: []int{401},
	}, func(ctx context.Context, _ *struct{}) (*programsOutput, error) {
		userID, _ := userFrom(ctx)
		programs, err := svc.List(ctx, userID)
		if err != nil {
			return nil, toProblem(ctx, logger, err)
		}
		body := make([]ProgramBody, len(programs))
		for i, p := range programs {
			body[i] = ProgramBody{
				ID: p.ID, PlanKind: p.PlanKind, RaceTarget: p.RaceTarget, RaceDistanceKm: p.RaceDistanceKm,
				RaceDate: p.RaceDate, GoalTime: p.GoalTime, WeeksTotal: p.WeeksTotal, CurrentWeek: p.CurrentWeek,
				DaysUntilRace: p.DaysUntilRace, FromCoach: p.FromCoach, ReviewWeek: p.ReviewWeek, CheckinDue: p.CheckinDue,
			}
		}
		return &programsOutput{Body: body}, nil
	})

	huma.Register(api, huma.Operation{
		OperationID: "archivePlan", Method: http.MethodPost, Path: "/training/plans/{id}/archive",
		Summary: "Archive a plan (progress is kept)", Tags: tags, Middlewares: signedIn, Errors: []int{401},
	}, func(ctx context.Context, in *idPathInput) (*resultOutput, error) {
		userID, _ := userFrom(ctx)
		if err := svc.Archive(ctx, userID, in.ID); err != nil {
			return nil, toProblem(ctx, logger, err)
		}
		return &resultOutput{Body: ResultBody{Status: "info", Message: "Plan archived."}}, nil
	})

	huma.Register(api, huma.Operation{
		OperationID: "exportTrainingCalendar", Method: http.MethodGet, Path: "/training/calendar.ics",
		Summary: "Download the active plans as an .ics calendar (all-day events)",
		Tags:    tags, Middlewares: signedIn, Errors: []int{401, 404},
	}, func(ctx context.Context, _ *struct{}) (*calendarOutput, error) {
		userID, _ := userFrom(ctx)
		calendar, err := svc.CalendarExport(ctx, userID)
		if err != nil {
			return nil, toProblem(ctx, logger, err)
		}
		return &calendarOutput{
			ContentType:        "text/calendar; charset=utf-8",
			ContentDisposition: `attachment; filename="coachin-training-plan.ics"`,
			Body:               []byte(calendar),
		}, nil
	})
}
