// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package queries

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

const consumeAuthToken = `-- name: ConsumeAuthToken :one
UPDATE app.auth_tokens SET used_at = now()
WHERE token_hash = $1
  AND purpose = $2
  AND used_at IS NULL
  AND expires_at > now()
RETURNING user_id
`

type ConsumeAuthTokenParams struct {
	TokenHash []byte `json:"token_hash"`
	Purpose   string `json:"purpose"`
}

// Marks a valid, unused token as used and returns its user; no row when the
// token is unknown, expired, already used, or for another purpose.
func (q *Queries) ConsumeAuthToken(ctx context.Context, arg ConsumeAuthTokenParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, consumeAuthToken, arg.TokenHash, arg.Purpose)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const createAuthToken = `-- name: CreateAuthToken :exec
INSERT INTO app.auth_tokens (token_hash, user_id, purpose, expires_at)
VALUES ($1, $2, $3, $4)
`

type CreateAuthTokenParams struct {
	TokenHash []byte    `json:"token_hash"`
	UserID    uuid.UUID `json:"user_id"`
	Purpose   string    `json:"purpose"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateAuthToken(ctx context.Context, arg CreateAuthTokenParams) error {
	_, err := q.db.Exec(ctx, createAuthToken,
		arg.TokenHash,
		arg.UserID,
		arg.Purpose,
		arg.ExpiresAt,
	)
	return err
}

const createProfile = `-- name: CreateProfile :exec
INSERT INTO public.profiles (id, email, full_name)
VALUES ($1, $2, $3)
`

type CreateProfileParams struct {
	ID       uuid.UUID `json:"id"`
	Email    *string   `json:"email"`
	FullName *string   `json:"full_name"`
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) error {
	_, err := q.db.Exec(ctx, createProfile, arg.ID, arg.Email, arg.FullName)
	return err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO app.sessions (id_hash, user_id, expires_at, user_agent, ip)
VALUES ($1, $2, $3, $4, $5::inet)
`

type CreateSessionParams struct {
	IDHash    []byte      `json:"id_hash"`
	UserID    uuid.UUID   `json:"user_id"`
	ExpiresAt time.Time   `json:"expires_at"`
	UserAgent *string     `json:"user_agent"`
	Ip        *netip.Addr `json:"ip"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.IDHash,
		arg.UserID,
		arg.ExpiresAt,
		arg.UserAgent,
		arg.Ip,
	)
	return err
}

const createUser = `-- name: CreateUser :one

INSERT INTO public.users (email, password_hash)
VALUES ($1::citext, $2)
RETURNING id, email::text AS email, created_at
`

type CreateUserParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
}

type CreateUserRow struct {
	ID        uuid.UUID `json:"id"`
	Email     string    `json:"email"`
	CreatedAt time.Time `json:"created_at"`
}

// Accounts, sessions, and email tokens. Run with the coachin_auth pool.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash)
	var i CreateUserRow
	err := row.Scan(&i.ID, &i.Email, &i.CreatedAt)
	return i, err
}

const deleteOtherUserSessions = `-- name: DeleteOtherUserSessions :exec
DELETE FROM app.sessions WHERE user_id = $1 AND id_hash <> $2
`

type DeleteOtherUserSessionsParams struct {
	UserID     uuid.UUID `json:"user_id"`
	KeepIDHash []byte    `json:"keep_id_hash"`
}

func (q *Queries) DeleteOtherUserSessions(ctx context.Context, arg DeleteOtherUserSessionsParams) error {
	_, err := q.db.Exec(ctx, deleteOtherUserSessions, arg.UserID, arg.KeepIDHash)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM app.sessions WHERE id_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, idHash []byte) error {
	_, err := q.db.Exec(ctx, deleteSession, idHash)
	return err
}

const deleteUserSessions = `-- name: DeleteUserSessions :exec
DELETE FROM app.sessions WHERE user_id = $1
`

func (q *Queries) DeleteUserSessions(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserSessions, userID)
	return err
}

const getProfileSummary = `-- name: GetProfileSummary :one
SELECT full_name, role FROM public.profiles WHERE id = $1
`

type GetProfileSummaryRow struct {
	FullName *string `json:"full_name"`
	Role     *string `json:"role"`
}

func (q *Queries) GetProfileSummary(ctx context.Context, id uuid.UUID) (GetProfileSummaryRow, error) {
	row := q.db.QueryRow(ctx, getProfileSummary, id)
	var i GetProfileSummaryRow
	err := row.Scan(&i.FullName, &i.Role)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT user_id, last_seen_at, expires_at
FROM app.sessions
WHERE id_hash = $1 AND expires_at > now()
`

type GetSessionRow struct {
	UserID     uuid.UUID `json:"user_id"`
	LastSeenAt time.Time `json:"last_seen_at"`
	ExpiresAt  time.Time `json:"expires_at"`
}

func (q *Queries) GetSession(ctx context.Context, idHash []byte) (GetSessionRow, error) {
	row := q.db.QueryRow(ctx, getSession, idHash)
	var i GetSessionRow
	err := row.Scan(&i.UserID, &i.LastSeenAt, &i.ExpiresAt)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email::text AS email, password_hash, email_verified_at
FROM public.users
WHERE email = $1::citext
`

type GetUserByEmailRow struct {
	ID              uuid.UUID  `json:"id"`
	Email           string     `json:"email"`
	PasswordHash    string     `json:"password_hash"`
	EmailVerifiedAt *time.Time `json:"email_verified_at"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email::text AS email, password_hash, email_verified_at
FROM public.users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID              uuid.UUID  `json:"id"`
	Email           string     `json:"email"`
	PasswordHash    string     `json:"password_hash"`
	EmailVerifiedAt *time.Time `json:"email_verified_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
	)
	return i, err
}

const markEmailVerified = `-- name: MarkEmailVerified :exec
UPDATE public.users SET email_verified_at = COALESCE(email_verified_at, now()), updated_at = now()
WHERE id = $1
`

func (q *Queries) MarkEmailVerified(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markEmailVerified, id)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE app.sessions SET last_seen_at = now(), expires_at = $1
WHERE id_hash = $2
`

type TouchSessionParams struct {
	ExpiresAt time.Time `json:"expires_at"`
	IDHash    []byte    `json:"id_hash"`
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.Exec(ctx, touchSession, arg.ExpiresAt, arg.IDHash)
	return err
}

const updatePasswordHash = `-- name: UpdatePasswordHash :exec
UPDATE public.users SET password_hash = $1, updated_at = now()
WHERE id = $2
`

type UpdatePasswordHashParams struct {
	PasswordHash string    `json:"password_hash"`
	ID           uuid.UUID `json:"id"`
}

func (q *Queries) UpdatePasswordHash(ctx context.Context, arg UpdatePasswordHashParams) error {
	_, err := q.db.Exec(ctx, updatePasswordHash, arg.PasswordHash, arg.ID)
	return err
}
