// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: calendar.sql

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const listPlanItemsInWeeks = `-- name: ListPlanItemsInWeeks :many
SELECT i.id, i.plan_id, i.week, i.day_of_week, i.item_type, i.title, i.description, i.details, i.is_completed
FROM public.plan_items i
JOIN public.training_plans p ON p.id = i.plan_id
WHERE p.user_id = $1
  -- Parallel arrays: the i-th plan is in its week i (unnests zip in step).
  AND (i.plan_id, i.week) IN (SELECT unnest($2::uuid[]), unnest($3::int[]))
ORDER BY p.plan_kind, p.created_at, i.id
`

type ListPlanItemsInWeeksParams struct {
	UserID  uuid.UUID   `json:"user_id"`
	PlanIds []uuid.UUID `json:"plan_ids"`
	Weeks   []int32     `json:"weeks"`
}

type ListPlanItemsInWeeksRow struct {
	ID          uuid.UUID `json:"id"`
	PlanID      uuid.UUID `json:"plan_id"`
	Week        int32     `json:"week"`
	DayOfWeek   int16     `json:"day_of_week"`
	ItemType    string    `json:"item_type"`
	Title       string    `json:"title"`
	Description *string   `json:"description"`
	Details     []byte    `json:"details"`
	IsCompleted bool      `json:"is_completed"`
}

// Every item of each (plan, week) pair.
func (q *Queries) ListPlanItemsInWeeks(ctx context.Context, arg ListPlanItemsInWeeksParams) ([]ListPlanItemsInWeeksRow, error) {
	rows, err := q.db.Query(ctx, listPlanItemsInWeeks, arg.UserID, arg.PlanIds, arg.Weeks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlanItemsInWeeksRow{}
	for rows.Next() {
		var i ListPlanItemsInWeeksRow
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.Week,
			&i.DayOfWeek,
			&i.ItemType,
			&i.Title,
			&i.Description,
			&i.Details,
			&i.IsCompleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchedulesBetween = `-- name: ListSchedulesBetween :many

SELECT s.sport_type_id, st.name AS sport_name, s.day_of_week, s."time", s.starts_on, s.ends_on
FROM public.schedules s
LEFT JOIN public.sport_types st ON st.id = s.sport_type_id
WHERE s.user_id = $1::uuid
  AND (s.starts_on IS NULL OR s.starts_on <= CAST($2::text AS date))
  AND (s.ends_on IS NULL OR s.ends_on >= CAST($3::text AS date))
ORDER BY s."time" NULLS LAST, s.created_at, s.id
`

type ListSchedulesBetweenParams struct {
	UserID   uuid.UUID `json:"user_id"`
	ToDate   string    `json:"to_date"`
	FromDate string    `json:"from_date"`
}

type ListSchedulesBetweenRow struct {
	SportTypeID *int64      `json:"sport_type_id"`
	SportName   *string     `json:"sport_name"`
	DayOfWeek   int16       `json:"day_of_week"`
	Time        pgtype.Time `json:"time"`
	StartsOn    pgtype.Date `json:"starts_on"`
	EndsOn      pgtype.Date `json:"ends_on"`
}

// Calendar: a Monday–Sunday week on real dates.
// Run with the coachin_app pool inside store.WithUser.
// Fixed sessions whose starts_on/ends_on window overlaps from..to.
func (q *Queries) ListSchedulesBetween(ctx context.Context, arg ListSchedulesBetweenParams) ([]ListSchedulesBetweenRow, error) {
	rows, err := q.db.Query(ctx, listSchedulesBetween, arg.UserID, arg.ToDate, arg.FromDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSchedulesBetweenRow{}
	for rows.Next() {
		var i ListSchedulesBetweenRow
		if err := rows.Scan(
			&i.SportTypeID,
			&i.SportName,
			&i.DayOfWeek,
			&i.Time,
			&i.StartsOn,
			&i.EndsOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
