// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: coaching.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const assignCoachSchedule = `-- name: AssignCoachSchedule :one
SELECT public.assign_coach_schedule_to_student($1)::text
`

func (q *Queries) AssignCoachSchedule(ctx context.Context, studentID uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, assignCoachSchedule, studentID)
	var column_1 string
	err := row.Scan(&column_1)
	return column_1, err
}

const coachedTrainee = `-- name: CoachedTrainee :one
SELECT p.id, p.full_name, p.email, p.nutrition_sharing_enabled
FROM public.coaching_relationships cr JOIN public.profiles p ON p.id = cr.student_id
WHERE cr.coach_id = $1 AND cr.student_id = $2 AND cr.status = 'active'
LIMIT 1
`

type CoachedTraineeParams struct {
	CoachID   uuid.UUID `json:"coach_id"`
	TraineeID uuid.UUID `json:"trainee_id"`
}

type CoachedTraineeRow struct {
	ID                      uuid.UUID `json:"id"`
	FullName                *string   `json:"full_name"`
	Email                   *string   `json:"email"`
	NutritionSharingEnabled bool      `json:"nutrition_sharing_enabled"`
}

// The trainee when actively coached by this coach (any sport).
func (q *Queries) CoachedTrainee(ctx context.Context, arg CoachedTraineeParams) (CoachedTraineeRow, error) {
	row := q.db.QueryRow(ctx, coachedTrainee, arg.CoachID, arg.TraineeID)
	var i CoachedTraineeRow
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.NutritionSharingEnabled,
	)
	return i, err
}

const joinCoachingByCode = `-- name: JoinCoachingByCode :one
SELECT public.join_coaching_via_invite_code($1)::text
`

func (q *Queries) JoinCoachingByCode(ctx context.Context, code string) (string, error) {
	row := q.db.QueryRow(ctx, joinCoachingByCode, code)
	var column_1 string
	err := row.Scan(&column_1)
	return column_1, err
}

const listInviteCodes = `-- name: ListInviteCodes :many
SELECT c.code, c.is_active, c.expires_at, c.sport_type_id, st.name AS sport_name
FROM public.coach_invite_codes c LEFT JOIN public.sport_types st ON st.id = c.sport_type_id
WHERE c.coach_id = $1
ORDER BY c.updated_at DESC
`

type ListInviteCodesRow struct {
	Code        string     `json:"code"`
	IsActive    bool       `json:"is_active"`
	ExpiresAt   *time.Time `json:"expires_at"`
	SportTypeID int64      `json:"sport_type_id"`
	SportName   *string    `json:"sport_name"`
}

func (q *Queries) ListInviteCodes(ctx context.Context, coachID uuid.UUID) ([]ListInviteCodesRow, error) {
	rows, err := q.db.Query(ctx, listInviteCodes, coachID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInviteCodesRow{}
	for rows.Next() {
		var i ListInviteCodesRow
		if err := rows.Scan(
			&i.Code,
			&i.IsActive,
			&i.ExpiresAt,
			&i.SportTypeID,
			&i.SportName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrainees = `-- name: ListTrainees :many
SELECT p.id, p.email, p.full_name, p.avatar_url, COALESCE(p.xp, 0)::bigint AS xp, COALESCE(p.level, 1)::bigint AS level,
       p.league_tier, p.nutrition_sharing_enabled, cr.sport_type_id, st.name AS sport_name
FROM public.coaching_relationships cr
JOIN public.profiles p ON p.id = cr.student_id
LEFT JOIN public.sport_types st ON st.id = cr.sport_type_id
WHERE cr.coach_id = $1 AND cr.status = 'active'
ORDER BY cr.created_at
`

type ListTraineesRow struct {
	ID                      uuid.UUID `json:"id"`
	Email                   *string   `json:"email"`
	FullName                *string   `json:"full_name"`
	AvatarUrl               *string   `json:"avatar_url"`
	Xp                      int64     `json:"xp"`
	Level                   int64     `json:"level"`
	LeagueTier              *string   `json:"league_tier"`
	NutritionSharingEnabled bool      `json:"nutrition_sharing_enabled"`
	SportTypeID             *int64    `json:"sport_type_id"`
	SportName               *string   `json:"sport_name"`
}

// The coach's active relationships (one per sport) with each trainee's public profile.
func (q *Queries) ListTrainees(ctx context.Context, coachID uuid.UUID) ([]ListTraineesRow, error) {
	rows, err := q.db.Query(ctx, listTrainees, coachID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTraineesRow{}
	for rows.Next() {
		var i ListTraineesRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FullName,
			&i.AvatarUrl,
			&i.Xp,
			&i.Level,
			&i.LeagueTier,
			&i.NutritionSharingEnabled,
			&i.SportTypeID,
			&i.SportName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const planItemsInWeeks = `-- name: PlanItemsInWeeks :many
SELECT plan_id, week, item_type, is_completed, details FROM public.plan_items
WHERE plan_id = ANY($1::uuid[]) AND week = ANY($2::int[])
`

type PlanItemsInWeeksParams struct {
	PlanIds []uuid.UUID `json:"plan_ids"`
	Weeks   []int32     `json:"weeks"`
}

type PlanItemsInWeeksRow struct {
	PlanID      uuid.UUID `json:"plan_id"`
	Week        int32     `json:"week"`
	ItemType    string    `json:"item_type"`
	IsCompleted bool      `json:"is_completed"`
	Details     []byte    `json:"details"`
}

func (q *Queries) PlanItemsInWeeks(ctx context.Context, arg PlanItemsInWeeksParams) ([]PlanItemsInWeeksRow, error) {
	rows, err := q.db.Query(ctx, planItemsInWeeks, arg.PlanIds, arg.Weeks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlanItemsInWeeksRow{}
	for rows.Next() {
		var i PlanItemsInWeeksRow
		if err := rows.Scan(
			&i.PlanID,
			&i.Week,
			&i.ItemType,
			&i.IsCompleted,
			&i.Details,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sportExists = `-- name: SportExists :one
SELECT EXISTS (SELECT 1 FROM public.sport_types WHERE id = $1)::bool AS found
`

func (q *Queries) SportExists(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRow(ctx, sportExists, id)
	var found bool
	err := row.Scan(&found)
	return found, err
}

const traineeActivePlans = `-- name: TraineeActivePlans :many
SELECT id, user_id, plan_kind, created_at, weeks_total FROM public.training_plans
WHERE user_id = ANY($1::uuid[]) AND status = 'active'
`

type TraineeActivePlansRow struct {
	ID         uuid.UUID `json:"id"`
	UserID     uuid.UUID `json:"user_id"`
	PlanKind   string    `json:"plan_kind"`
	CreatedAt  time.Time `json:"created_at"`
	WeeksTotal int32     `json:"weeks_total"`
}

func (q *Queries) TraineeActivePlans(ctx context.Context, ids []uuid.UUID) ([]TraineeActivePlansRow, error) {
	rows, err := q.db.Query(ctx, traineeActivePlans, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TraineeActivePlansRow{}
	for rows.Next() {
		var i TraineeActivePlansRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PlanKind,
			&i.CreatedAt,
			&i.WeeksTotal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const traineeLoggedDates = `-- name: TraineeLoggedDates :many
SELECT DISTINCT user_id, date::text AS on_date FROM public.logs
WHERE user_id = ANY($1::uuid[]) AND status = 'completed'
  AND date BETWEEN CAST($2::text AS date) AND CAST($3::text AS date)
`

type TraineeLoggedDatesParams struct {
	Ids      []uuid.UUID `json:"ids"`
	FromDate string      `json:"from_date"`
	ToDate   string      `json:"to_date"`
}

type TraineeLoggedDatesRow struct {
	UserID *uuid.UUID `json:"user_id"`
	OnDate string     `json:"on_date"`
}

func (q *Queries) TraineeLoggedDates(ctx context.Context, arg TraineeLoggedDatesParams) ([]TraineeLoggedDatesRow, error) {
	rows, err := q.db.Query(ctx, traineeLoggedDates, arg.Ids, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TraineeLoggedDatesRow{}
	for rows.Next() {
		var i TraineeLoggedDatesRow
		if err := rows.Scan(&i.UserID, &i.OnDate); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const traineeMealPlanTargets = `-- name: TraineeMealPlanTargets :one
SELECT kcal_target::float8 AS kcal, protein_g_target::float8 AS protein_g FROM public.meal_plans
WHERE user_id = $1 AND status = 'active'
LIMIT 1
`

type TraineeMealPlanTargetsRow struct {
	Kcal     float64 `json:"kcal"`
	ProteinG float64 `json:"protein_g"`
}

func (q *Queries) TraineeMealPlanTargets(ctx context.Context, userID uuid.UUID) (TraineeMealPlanTargetsRow, error) {
	row := q.db.QueryRow(ctx, traineeMealPlanTargets, userID)
	var i TraineeMealPlanTargetsRow
	err := row.Scan(&i.Kcal, &i.ProteinG)
	return i, err
}

const traineeMealsSince = `-- name: TraineeMealsSince :many
SELECT m.id, m.date::text AS on_date, m.meal_type, COALESCE(f.name, NULLIF(m.free_text, ''), 'Logged meal')::text AS label,
       COALESCE(m.kcal, 0)::float8 AS kcal, COALESCE(m.protein_g, 0)::float8 AS protein_g
FROM public.meal_logs m LEFT JOIN public.foods f ON f.id = m.food_id
WHERE m.user_id = $1 AND m.date >= CAST($2::text AS date)
ORDER BY m.date DESC, m.created_at
`

type TraineeMealsSinceParams struct {
	UserID   uuid.UUID `json:"user_id"`
	FromDate string    `json:"from_date"`
}

type TraineeMealsSinceRow struct {
	ID       uuid.UUID `json:"id"`
	OnDate   string    `json:"on_date"`
	MealType string    `json:"meal_type"`
	Label    string    `json:"label"`
	Kcal     float64   `json:"kcal"`
	ProteinG float64   `json:"protein_g"`
}

func (q *Queries) TraineeMealsSince(ctx context.Context, arg TraineeMealsSinceParams) ([]TraineeMealsSinceRow, error) {
	rows, err := q.db.Query(ctx, traineeMealsSince, arg.UserID, arg.FromDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TraineeMealsSinceRow{}
	for rows.Next() {
		var i TraineeMealsSinceRow
		if err := rows.Scan(
			&i.ID,
			&i.OnDate,
			&i.MealType,
			&i.Label,
			&i.Kcal,
			&i.ProteinG,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const traineeRoutineDays = `-- name: TraineeRoutineDays :many
SELECT day_of_week, starts_on, ends_on FROM public.schedules
WHERE user_id = $1
`

type TraineeRoutineDaysRow struct {
	DayOfWeek int16       `json:"day_of_week"`
	StartsOn  pgtype.Date `json:"starts_on"`
	EndsOn    pgtype.Date `json:"ends_on"`
}

func (q *Queries) TraineeRoutineDays(ctx context.Context, userID *uuid.UUID) ([]TraineeRoutineDaysRow, error) {
	rows, err := q.db.Query(ctx, traineeRoutineDays, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TraineeRoutineDaysRow{}
	for rows.Next() {
		var i TraineeRoutineDaysRow
		if err := rows.Scan(&i.DayOfWeek, &i.StartsOn, &i.EndsOn); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const traineeScheduledDays = `-- name: TraineeScheduledDays :many
SELECT DISTINCT user_id, day_of_week FROM public.schedules WHERE user_id = ANY($1::uuid[])
`

type TraineeScheduledDaysRow struct {
	UserID    *uuid.UUID `json:"user_id"`
	DayOfWeek int16      `json:"day_of_week"`
}

func (q *Queries) TraineeScheduledDays(ctx context.Context, ids []uuid.UUID) ([]TraineeScheduledDaysRow, error) {
	rows, err := q.db.Query(ctx, traineeScheduledDays, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TraineeScheduledDaysRow{}
	for rows.Next() {
		var i TraineeScheduledDaysRow
		if err := rows.Scan(&i.UserID, &i.DayOfWeek); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const traineeSupplementLogsSince = `-- name: TraineeSupplementLogsSince :many
SELECT supplement_id, date::text AS on_date FROM public.supplement_logs
WHERE user_id = $1 AND date >= CAST($2::text AS date)
`

type TraineeSupplementLogsSinceParams struct {
	UserID   uuid.UUID `json:"user_id"`
	FromDate string    `json:"from_date"`
}

type TraineeSupplementLogsSinceRow struct {
	SupplementID uuid.UUID `json:"supplement_id"`
	OnDate       string    `json:"on_date"`
}

func (q *Queries) TraineeSupplementLogsSince(ctx context.Context, arg TraineeSupplementLogsSinceParams) ([]TraineeSupplementLogsSinceRow, error) {
	rows, err := q.db.Query(ctx, traineeSupplementLogsSince, arg.UserID, arg.FromDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TraineeSupplementLogsSinceRow{}
	for rows.Next() {
		var i TraineeSupplementLogsSinceRow
		if err := rows.Scan(&i.SupplementID, &i.OnDate); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const traineeSupplements = `-- name: TraineeSupplements :many
SELECT id, name, dose, schedule_type, days_of_week, created_at FROM public.supplements
WHERE user_id = $1 ORDER BY created_at
`

type TraineeSupplementsRow struct {
	ID           uuid.UUID `json:"id"`
	Name         string    `json:"name"`
	Dose         *string   `json:"dose"`
	ScheduleType string    `json:"schedule_type"`
	DaysOfWeek   []int16   `json:"days_of_week"`
	CreatedAt    time.Time `json:"created_at"`
}

func (q *Queries) TraineeSupplements(ctx context.Context, userID uuid.UUID) ([]TraineeSupplementsRow, error) {
	rows, err := q.db.Query(ctx, traineeSupplements, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TraineeSupplementsRow{}
	for rows.Next() {
		var i TraineeSupplementsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Dose,
			&i.ScheduleType,
			&i.DaysOfWeek,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const traineeTrainingDays = `-- name: TraineeTrainingDays :many
SELECT tp.id AS plan_id, tp.created_at, tp.weeks_total, pi.week, pi.day_of_week
FROM public.training_plans tp JOIN public.plan_items pi ON pi.plan_id = tp.id
WHERE tp.user_id = $1 AND tp.status = 'active'
`

type TraineeTrainingDaysRow struct {
	PlanID     uuid.UUID `json:"plan_id"`
	CreatedAt  time.Time `json:"created_at"`
	WeeksTotal int32     `json:"weeks_total"`
	Week       int32     `json:"week"`
	DayOfWeek  int16     `json:"day_of_week"`
}

// Plan items (with their plan's start) and routine days, for the due-day window.
func (q *Queries) TraineeTrainingDays(ctx context.Context, userID uuid.UUID) ([]TraineeTrainingDaysRow, error) {
	rows, err := q.db.Query(ctx, traineeTrainingDays, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TraineeTrainingDaysRow{}
	for rows.Next() {
		var i TraineeTrainingDaysRow
		if err := rows.Scan(
			&i.PlanID,
			&i.CreatedAt,
			&i.WeeksTotal,
			&i.Week,
			&i.DayOfWeek,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertInviteCode = `-- name: UpsertInviteCode :exec
INSERT INTO public.coach_invite_codes (coach_id, sport_type_id, code, is_active, expires_at, updated_at)
VALUES ($1, $2, $3, true, NULL, now())
ON CONFLICT (coach_id, sport_type_id) DO UPDATE
SET code = EXCLUDED.code, is_active = true, expires_at = NULL, updated_at = now()
`

type UpsertInviteCodeParams struct {
	CoachID     uuid.UUID `json:"coach_id"`
	SportTypeID int64     `json:"sport_type_id"`
	Code        string    `json:"code"`
}

func (q *Queries) UpsertInviteCode(ctx context.Context, arg UpsertInviteCodeParams) error {
	_, err := q.db.Exec(ctx, upsertInviteCode, arg.CoachID, arg.SportTypeID, arg.Code)
	return err
}

const userRole = `-- name: UserRole :one
SELECT COALESCE(role, 'student')::text AS role FROM public.profiles WHERE id = $1
`

func (q *Queries) UserRole(ctx context.Context, userID uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, userRole, userID)
	var role string
	err := row.Scan(&role)
	return role, err
}
