// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: community.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const clearPrimaryClub = `-- name: ClearPrimaryClub :exec
UPDATE public.club_members SET is_primary = false WHERE user_id = $1 AND is_primary
`

func (q *Queries) ClearPrimaryClub(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearPrimaryClub, userID)
	return err
}

const createClubWithOwner = `-- name: CreateClubWithOwner :one
SELECT public.create_club_with_owner($1, $2, $3)::text
`

type CreateClubWithOwnerParams struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Code        string `json:"code"`
}

func (q *Queries) CreateClubWithOwner(ctx context.Context, arg CreateClubWithOwnerParams) (string, error) {
	row := q.db.QueryRow(ctx, createClubWithOwner, arg.Name, arg.Description, arg.Code)
	var column_1 string
	err := row.Scan(&column_1)
	return column_1, err
}

const createTrainingGroup = `-- name: CreateTrainingGroup :one
SELECT public.create_training_group($1)::text
`

func (q *Queries) CreateTrainingGroup(ctx context.Context, name string) (string, error) {
	row := q.db.QueryRow(ctx, createTrainingGroup, name)
	var column_1 string
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteClubMembership = `-- name: DeleteClubMembership :one
DELETE FROM public.club_members WHERE user_id = $1 AND club_id = $2
RETURNING is_primary
`

type DeleteClubMembershipParams struct {
	UserID uuid.UUID `json:"user_id"`
	ClubID uuid.UUID `json:"club_id"`
}

func (q *Queries) DeleteClubMembership(ctx context.Context, arg DeleteClubMembershipParams) (bool, error) {
	row := q.db.QueryRow(ctx, deleteClubMembership, arg.UserID, arg.ClubID)
	var is_primary bool
	err := row.Scan(&is_primary)
	return is_primary, err
}

const deleteFollow = `-- name: DeleteFollow :execrows
DELETE FROM public.social_graph WHERE follower_id = $1 AND following_id = $2
`

type DeleteFollowParams struct {
	FollowerID  *uuid.UUID `json:"follower_id"`
	FollowingID *uuid.UUID `json:"following_id"`
}

func (q *Queries) DeleteFollow(ctx context.Context, arg DeleteFollowParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFollow, arg.FollowerID, arg.FollowingID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const evaluateGroupDays = `-- name: EvaluateGroupDays :one
SELECT public.evaluate_group_days($1)::text
`

// Settles past days (streak + member bonus XP, FORMULAS §2 Group streak); idempotent.
func (q *Queries) EvaluateGroupDays(ctx context.Context, groupID uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, evaluateGroupDays, groupID)
	var column_1 string
	err := row.Scan(&column_1)
	return column_1, err
}

const groupMembers = `-- name: GroupMembers :many
SELECT gm.group_id, p.id, p.full_name, p.avatar_url
FROM public.group_members gm JOIN public.profile_cards p ON p.id = gm.user_id
WHERE gm.group_id = ANY($1::uuid[])
ORDER BY gm.joined_at
`

type GroupMembersRow struct {
	GroupID   uuid.UUID `json:"group_id"`
	ID        uuid.UUID `json:"id"`
	FullName  *string   `json:"full_name"`
	AvatarUrl *string   `json:"avatar_url"`
}

func (q *Queries) GroupMembers(ctx context.Context, ids []uuid.UUID) ([]GroupMembersRow, error) {
	rows, err := q.db.Query(ctx, groupMembers, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GroupMembersRow{}
	for rows.Next() {
		var i GroupMembersRow
		if err := rows.Scan(
			&i.GroupID,
			&i.ID,
			&i.FullName,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const groupTrainedToday = `-- name: GroupTrainedToday :one
SELECT public.group_trained_today($1)::uuid[] AS ids
`

func (q *Queries) GroupTrainedToday(ctx context.Context, groupID uuid.UUID) ([]uuid.UUID, error) {
	row := q.db.QueryRow(ctx, groupTrainedToday, groupID)
	var ids []uuid.UUID
	err := row.Scan(&ids)
	return ids, err
}

const groupsByIDs = `-- name: GroupsByIDs :many
SELECT id, name, invite_code, streak_count, best_streak FROM public.training_groups
WHERE id = ANY($1::uuid[]) ORDER BY created_at
`

type GroupsByIDsRow struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	InviteCode  string    `json:"invite_code"`
	StreakCount int32     `json:"streak_count"`
	BestStreak  int32     `json:"best_streak"`
}

func (q *Queries) GroupsByIDs(ctx context.Context, ids []uuid.UUID) ([]GroupsByIDsRow, error) {
	rows, err := q.db.Query(ctx, groupsByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GroupsByIDsRow{}
	for rows.Next() {
		var i GroupsByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.InviteCode,
			&i.StreakCount,
			&i.BestStreak,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertFollow = `-- name: InsertFollow :exec
INSERT INTO public.social_graph (follower_id, following_id) VALUES ($1, $2)
`

type InsertFollowParams struct {
	FollowerID  *uuid.UUID `json:"follower_id"`
	FollowingID *uuid.UUID `json:"following_id"`
}

func (q *Queries) InsertFollow(ctx context.Context, arg InsertFollowParams) error {
	_, err := q.db.Exec(ctx, insertFollow, arg.FollowerID, arg.FollowingID)
	return err
}

const isClubMember = `-- name: IsClubMember :one
SELECT EXISTS (SELECT 1 FROM public.club_members WHERE club_id = $1 AND user_id = $2)::bool AS member
`

type IsClubMemberParams struct {
	ClubID uuid.UUID `json:"club_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) IsClubMember(ctx context.Context, arg IsClubMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isClubMember, arg.ClubID, arg.UserID)
	var member bool
	err := row.Scan(&member)
	return member, err
}

const joinClubByCode = `-- name: JoinClubByCode :one
SELECT public.join_club_via_invite_code($1)::text
`

func (q *Queries) JoinClubByCode(ctx context.Context, code string) (string, error) {
	row := q.db.QueryRow(ctx, joinClubByCode, code)
	var column_1 string
	err := row.Scan(&column_1)
	return column_1, err
}

const joinTrainingGroup = `-- name: JoinTrainingGroup :one
SELECT public.join_training_group($1)::text
`

func (q *Queries) JoinTrainingGroup(ctx context.Context, code string) (string, error) {
	row := q.db.QueryRow(ctx, joinTrainingGroup, code)
	var column_1 string
	err := row.Scan(&column_1)
	return column_1, err
}

const leaveTrainingGroup = `-- name: LeaveTrainingGroup :one
SELECT public.leave_training_group($1)::text
`

func (q *Queries) LeaveTrainingGroup(ctx context.Context, groupID uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, leaveTrainingGroup, groupID)
	var column_1 string
	err := row.Scan(&column_1)
	return column_1, err
}

const listClubMemberIDs = `-- name: ListClubMemberIDs :many
SELECT user_id FROM public.club_members WHERE club_id = $1
`

func (q *Queries) ListClubMemberIDs(ctx context.Context, clubID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listClubMemberIDs, clubID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClubMemberships = `-- name: ListClubMemberships :many
SELECT cm.club_id, c.name, c.invite_code, COALESCE(cm.role, 'member')::text AS role, cm.is_primary
FROM public.club_members cm JOIN public.clubs c ON c.id = cm.club_id
WHERE cm.user_id = $1
ORDER BY cm.joined_at
`

type ListClubMembershipsRow struct {
	ClubID     uuid.UUID `json:"club_id"`
	Name       string    `json:"name"`
	InviteCode string    `json:"invite_code"`
	Role       string    `json:"role"`
	IsPrimary  bool      `json:"is_primary"`
}

func (q *Queries) ListClubMemberships(ctx context.Context, userID uuid.UUID) ([]ListClubMembershipsRow, error) {
	rows, err := q.db.Query(ctx, listClubMemberships, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClubMembershipsRow{}
	for rows.Next() {
		var i ListClubMembershipsRow
		if err := rows.Scan(
			&i.ClubID,
			&i.Name,
			&i.InviteCode,
			&i.Role,
			&i.IsPrimary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFollowing = `-- name: ListFollowing :many
SELECT following_id FROM public.social_graph WHERE follower_id = $1 AND following_id IS NOT NULL
`

func (q *Queries) ListFollowing(ctx context.Context, userID *uuid.UUID) ([]*uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listFollowing, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*uuid.UUID{}
	for rows.Next() {
		var following_id *uuid.UUID
		if err := rows.Scan(&following_id); err != nil {
			return nil, err
		}
		items = append(items, following_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFollowingProfiles = `-- name: ListFollowingProfiles :many
SELECT p.id, p.full_name, p.avatar_url, COALESCE(p.level, 1)::bigint AS level, p.league_tier, COALESCE(p.xp, 0)::bigint AS xp
FROM public.social_graph g JOIN public.profile_cards p ON p.id = g.following_id
WHERE g.follower_id = $1
ORDER BY g.created_at
`

type ListFollowingProfilesRow struct {
	ID         uuid.UUID `json:"id"`
	FullName   *string   `json:"full_name"`
	AvatarUrl  *string   `json:"avatar_url"`
	Level      int64     `json:"level"`
	LeagueTier *string   `json:"league_tier"`
	Xp         int64     `json:"xp"`
}

func (q *Queries) ListFollowingProfiles(ctx context.Context, userID *uuid.UUID) ([]ListFollowingProfilesRow, error) {
	rows, err := q.db.Query(ctx, listFollowingProfiles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFollowingProfilesRow{}
	for rows.Next() {
		var i ListFollowingProfilesRow
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.AvatarUrl,
			&i.Level,
			&i.LeagueTier,
			&i.Xp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMyCoaches = `-- name: ListMyCoaches :many
SELECT p.id, p.full_name, p.avatar_url, COALESCE(p.level, 1)::bigint AS level, p.league_tier, st.name AS sport_name
FROM public.coaching_relationships cr JOIN public.profiles p ON p.id = cr.coach_id
LEFT JOIN public.sport_types st ON st.id = cr.sport_type_id
WHERE cr.student_id = $1 AND cr.status = 'active'
ORDER BY cr.created_at
`

type ListMyCoachesRow struct {
	ID         uuid.UUID `json:"id"`
	FullName   *string   `json:"full_name"`
	AvatarUrl  *string   `json:"avatar_url"`
	Level      int64     `json:"level"`
	LeagueTier *string   `json:"league_tier"`
	SportName  *string   `json:"sport_name"`
}

func (q *Queries) ListMyCoaches(ctx context.Context, userID uuid.UUID) ([]ListMyCoachesRow, error) {
	rows, err := q.db.Query(ctx, listMyCoaches, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMyCoachesRow{}
	for rows.Next() {
		var i ListMyCoachesRow
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.AvatarUrl,
			&i.Level,
			&i.LeagueTier,
			&i.SportName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loggedAnythingOn = `-- name: LoggedAnythingOn :one
SELECT EXISTS (SELECT 1 FROM public.logs WHERE user_id = $1 AND date = CAST($2::text AS date))::bool AS logged
`

type LoggedAnythingOnParams struct {
	UserID *uuid.UUID `json:"user_id"`
	OnDate string     `json:"on_date"`
}

func (q *Queries) LoggedAnythingOn(ctx context.Context, arg LoggedAnythingOnParams) (bool, error) {
	row := q.db.QueryRow(ctx, loggedAnythingOn, arg.UserID, arg.OnDate)
	var logged bool
	err := row.Scan(&logged)
	return logged, err
}

const markPrimaryClub = `-- name: MarkPrimaryClub :exec
UPDATE public.club_members SET is_primary = true WHERE user_id = $1 AND club_id = $2
`

type MarkPrimaryClubParams struct {
	UserID uuid.UUID `json:"user_id"`
	ClubID uuid.UUID `json:"club_id"`
}

func (q *Queries) MarkPrimaryClub(ctx context.Context, arg MarkPrimaryClubParams) error {
	_, err := q.db.Exec(ctx, markPrimaryClub, arg.UserID, arg.ClubID)
	return err
}

const myGroupIDs = `-- name: MyGroupIDs :many
SELECT group_id FROM public.group_members WHERE user_id = $1 ORDER BY joined_at
`

func (q *Queries) MyGroupIDs(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, myGroupIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var group_id uuid.UUID
		if err := rows.Scan(&group_id); err != nil {
			return nil, err
		}
		items = append(items, group_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const profileExists = `-- name: ProfileExists :one
SELECT EXISTS (SELECT 1 FROM public.profile_cards WHERE id = $1)::bool AS found
`

func (q *Queries) ProfileExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, profileExists, id)
	var found bool
	err := row.Scan(&found)
	return found, err
}

const promoteNextPrimaryClub = `-- name: PromoteNextPrimaryClub :exec
UPDATE public.club_members SET is_primary = true
WHERE id = (SELECT m.id FROM public.club_members m WHERE m.user_id = $1 ORDER BY m.joined_at LIMIT 1)
`

func (q *Queries) PromoteNextPrimaryClub(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, promoteNextPrimaryClub, userID)
	return err
}

const recentGroupDays = `-- name: RecentGroupDays :many
SELECT group_id, date::text AS on_date, all_trained FROM public.group_days
WHERE group_id = ANY($1::uuid[]) AND date >= CAST($2::text AS date)
ORDER BY date
`

type RecentGroupDaysParams struct {
	Ids      []uuid.UUID `json:"ids"`
	FromDate string      `json:"from_date"`
}

type RecentGroupDaysRow struct {
	GroupID    uuid.UUID `json:"group_id"`
	OnDate     string    `json:"on_date"`
	AllTrained bool      `json:"all_trained"`
}

func (q *Queries) RecentGroupDays(ctx context.Context, arg RecentGroupDaysParams) ([]RecentGroupDaysRow, error) {
	rows, err := q.db.Query(ctx, recentGroupDays, arg.Ids, arg.FromDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecentGroupDaysRow{}
	for rows.Next() {
		var i RecentGroupDaysRow
		if err := rows.Scan(&i.GroupID, &i.OnDate, &i.AllTrained); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPeople = `-- name: SearchPeople :many
SELECT p.id, p.full_name, p.avatar_url, COALESCE(p.level, 1)::bigint AS level, p.league_tier, COALESCE(p.xp, 0)::bigint AS xp,
       EXISTS (SELECT 1 FROM public.social_graph g WHERE g.follower_id = $1 AND g.following_id = p.id)::bool AS following
FROM public.profile_cards p
WHERE p.id <> $1
  AND ($2::text = ''
       OR p.full_name ILIKE '%' || replace(replace(replace($2::text, '\', '\\'), '%', '\%'), '_', '\_') || '%'
       OR p.id = public.user_id_by_email($2::text))
ORDER BY p.xp DESC NULLS LAST, p.id
LIMIT $4::int OFFSET $3::int
`

type SearchPeopleParams struct {
	UserID  *uuid.UUID `json:"user_id"`
	Term    string     `json:"term"`
	Skip    int32      `json:"skip"`
	MaxRows int32      `json:"max_rows"`
}

type SearchPeopleRow struct {
	ID         uuid.UUID `json:"id"`
	FullName   *string   `json:"full_name"`
	AvatarUrl  *string   `json:"avatar_url"`
	Level      int64     `json:"level"`
	LeagueTier *string   `json:"league_tier"`
	Xp         int64     `json:"xp"`
	Following  bool      `json:"following"`
}

// Name contains the term (wildcards literal), or the exact email; never the
// caller. Top lifetime XP first.
func (q *Queries) SearchPeople(ctx context.Context, arg SearchPeopleParams) ([]SearchPeopleRow, error) {
	rows, err := q.db.Query(ctx, searchPeople,
		arg.UserID,
		arg.Term,
		arg.Skip,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchPeopleRow{}
	for rows.Next() {
		var i SearchPeopleRow
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.AvatarUrl,
			&i.Level,
			&i.LeagueTier,
			&i.Xp,
			&i.Following,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const topStreakGroup = `-- name: TopStreakGroup :one
SELECT g.name, g.streak_count FROM public.group_members gm JOIN public.training_groups g ON g.id = gm.group_id
WHERE gm.user_id = $1 AND g.streak_count > 0
ORDER BY g.streak_count DESC, g.created_at
LIMIT 1
`

type TopStreakGroupRow struct {
	Name        string `json:"name"`
	StreakCount int32  `json:"streak_count"`
}

// The user's group with the longest live streak (the Today nudge).
func (q *Queries) TopStreakGroup(ctx context.Context, userID uuid.UUID) (TopStreakGroupRow, error) {
	row := q.db.QueryRow(ctx, topStreakGroup, userID)
	var i TopStreakGroupRow
	err := row.Scan(&i.Name, &i.StreakCount)
	return i, err
}

const totalXPBoard = `-- name: TotalXPBoard :many
SELECT id, full_name, avatar_url, COALESCE(level, 1)::bigint AS level, league_tier, COALESCE(xp, 0)::bigint AS xp
FROM public.profile_cards
WHERE $1::uuid[] IS NULL OR id = ANY($1::uuid[])
ORDER BY xp DESC NULLS LAST
LIMIT $2::int
`

type TotalXPBoardParams struct {
	Ids     []uuid.UUID `json:"ids"`
	MaxRows int32       `json:"max_rows"`
}

type TotalXPBoardRow struct {
	ID         uuid.UUID `json:"id"`
	FullName   *string   `json:"full_name"`
	AvatarUrl  *string   `json:"avatar_url"`
	Level      int64     `json:"level"`
	LeagueTier *string   `json:"league_tier"`
	Xp         int64     `json:"xp"`
}

// Lifetime-XP ranking (all users when ids is NULL).
func (q *Queries) TotalXPBoard(ctx context.Context, arg TotalXPBoardParams) ([]TotalXPBoardRow, error) {
	rows, err := q.db.Query(ctx, totalXPBoard, arg.Ids, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TotalXPBoardRow{}
	for rows.Next() {
		var i TotalXPBoardRow
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.AvatarUrl,
			&i.Level,
			&i.LeagueTier,
			&i.Xp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
