// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: community.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const clearPrimaryClub = `-- name: ClearPrimaryClub :exec
UPDATE public.club_members SET is_primary = false WHERE user_id = $1 AND is_primary
`

func (q *Queries) ClearPrimaryClub(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearPrimaryClub, userID)
	return err
}

const createClubWithOwner = `-- name: CreateClubWithOwner :one
SELECT public.create_club_with_owner($1, $2, $3)::text
`

type CreateClubWithOwnerParams struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Code        string `json:"code"`
}

func (q *Queries) CreateClubWithOwner(ctx context.Context, arg CreateClubWithOwnerParams) (string, error) {
	row := q.db.QueryRow(ctx, createClubWithOwner, arg.Name, arg.Description, arg.Code)
	var column_1 string
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteClubMembership = `-- name: DeleteClubMembership :one
DELETE FROM public.club_members WHERE user_id = $1 AND club_id = $2
RETURNING is_primary
`

type DeleteClubMembershipParams struct {
	UserID uuid.UUID `json:"user_id"`
	ClubID uuid.UUID `json:"club_id"`
}

func (q *Queries) DeleteClubMembership(ctx context.Context, arg DeleteClubMembershipParams) (bool, error) {
	row := q.db.QueryRow(ctx, deleteClubMembership, arg.UserID, arg.ClubID)
	var is_primary bool
	err := row.Scan(&is_primary)
	return is_primary, err
}

const isClubMember = `-- name: IsClubMember :one
SELECT EXISTS (SELECT 1 FROM public.club_members WHERE club_id = $1 AND user_id = $2)::bool AS member
`

type IsClubMemberParams struct {
	ClubID uuid.UUID `json:"club_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) IsClubMember(ctx context.Context, arg IsClubMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isClubMember, arg.ClubID, arg.UserID)
	var member bool
	err := row.Scan(&member)
	return member, err
}

const joinClubByCode = `-- name: JoinClubByCode :one
SELECT public.join_club_via_invite_code($1)::text
`

func (q *Queries) JoinClubByCode(ctx context.Context, code string) (string, error) {
	row := q.db.QueryRow(ctx, joinClubByCode, code)
	var column_1 string
	err := row.Scan(&column_1)
	return column_1, err
}

const listClubMemberIDs = `-- name: ListClubMemberIDs :many
SELECT user_id FROM public.club_members WHERE club_id = $1
`

func (q *Queries) ListClubMemberIDs(ctx context.Context, clubID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listClubMemberIDs, clubID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClubMemberships = `-- name: ListClubMemberships :many
SELECT cm.club_id, c.name, c.invite_code, COALESCE(cm.role, 'member')::text AS role, cm.is_primary
FROM public.club_members cm JOIN public.clubs c ON c.id = cm.club_id
WHERE cm.user_id = $1
ORDER BY cm.joined_at
`

type ListClubMembershipsRow struct {
	ClubID     uuid.UUID `json:"club_id"`
	Name       string    `json:"name"`
	InviteCode string    `json:"invite_code"`
	Role       string    `json:"role"`
	IsPrimary  bool      `json:"is_primary"`
}

func (q *Queries) ListClubMemberships(ctx context.Context, userID uuid.UUID) ([]ListClubMembershipsRow, error) {
	rows, err := q.db.Query(ctx, listClubMemberships, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClubMembershipsRow{}
	for rows.Next() {
		var i ListClubMembershipsRow
		if err := rows.Scan(
			&i.ClubID,
			&i.Name,
			&i.InviteCode,
			&i.Role,
			&i.IsPrimary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFollowing = `-- name: ListFollowing :many
SELECT following_id FROM public.social_graph WHERE follower_id = $1 AND following_id IS NOT NULL
`

func (q *Queries) ListFollowing(ctx context.Context, userID *uuid.UUID) ([]*uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listFollowing, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*uuid.UUID{}
	for rows.Next() {
		var following_id *uuid.UUID
		if err := rows.Scan(&following_id); err != nil {
			return nil, err
		}
		items = append(items, following_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPrimaryClub = `-- name: MarkPrimaryClub :exec
UPDATE public.club_members SET is_primary = true WHERE user_id = $1 AND club_id = $2
`

type MarkPrimaryClubParams struct {
	UserID uuid.UUID `json:"user_id"`
	ClubID uuid.UUID `json:"club_id"`
}

func (q *Queries) MarkPrimaryClub(ctx context.Context, arg MarkPrimaryClubParams) error {
	_, err := q.db.Exec(ctx, markPrimaryClub, arg.UserID, arg.ClubID)
	return err
}

const promoteNextPrimaryClub = `-- name: PromoteNextPrimaryClub :exec
UPDATE public.club_members SET is_primary = true
WHERE id = (SELECT m.id FROM public.club_members m WHERE m.user_id = $1 ORDER BY m.joined_at LIMIT 1)
`

func (q *Queries) PromoteNextPrimaryClub(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, promoteNextPrimaryClub, userID)
	return err
}

const totalXPBoard = `-- name: TotalXPBoard :many
SELECT id, full_name, avatar_url, COALESCE(level, 1)::bigint AS level, league_tier, COALESCE(xp, 0)::bigint AS xp
FROM public.profiles
WHERE $1::uuid[] IS NULL OR id = ANY($1::uuid[])
ORDER BY xp DESC NULLS LAST
LIMIT $2::int
`

type TotalXPBoardParams struct {
	Ids     []uuid.UUID `json:"ids"`
	MaxRows int32       `json:"max_rows"`
}

type TotalXPBoardRow struct {
	ID         uuid.UUID `json:"id"`
	FullName   *string   `json:"full_name"`
	AvatarUrl  *string   `json:"avatar_url"`
	Level      int64     `json:"level"`
	LeagueTier *string   `json:"league_tier"`
	Xp         int64     `json:"xp"`
}

// Lifetime-XP ranking (all users when ids is NULL).
func (q *Queries) TotalXPBoard(ctx context.Context, arg TotalXPBoardParams) ([]TotalXPBoardRow, error) {
	rows, err := q.db.Query(ctx, totalXPBoard, arg.Ids, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TotalXPBoardRow{}
	for rows.Next() {
		var i TotalXPBoardRow
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.AvatarUrl,
			&i.Level,
			&i.LeagueTier,
			&i.Xp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
