// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"database/sql/driver"
	"fmt"
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type LogStatus string

const (
	LogStatusCompleted LogStatus = "completed"
	LogStatusSkipped   LogStatus = "skipped"
	LogStatusMissed    LogStatus = "missed"
)

func (e *LogStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LogStatus(s)
	case string:
		*e = LogStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for LogStatus: %T", src)
	}
	return nil
}

type NullLogStatus struct {
	LogStatus LogStatus `json:"log_status"`
	Valid     bool      `json:"valid"` // Valid is true if LogStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLogStatus) Scan(value interface{}) error {
	if value == nil {
		ns.LogStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LogStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLogStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LogStatus), nil
}

type AppAuthToken struct {
	TokenHash []byte     `json:"token_hash"`
	UserID    uuid.UUID  `json:"user_id"`
	Purpose   string     `json:"purpose"`
	CreatedAt time.Time  `json:"created_at"`
	ExpiresAt time.Time  `json:"expires_at"`
	UsedAt    *time.Time `json:"used_at"`
}

type AppSession struct {
	IDHash     []byte      `json:"id_hash"`
	UserID     uuid.UUID   `json:"user_id"`
	CreatedAt  time.Time   `json:"created_at"`
	LastSeenAt time.Time   `json:"last_seen_at"`
	ExpiresAt  time.Time   `json:"expires_at"`
	UserAgent  *string     `json:"user_agent"`
	Ip         *netip.Addr `json:"ip"`
}

type BodyMeasurement struct {
	ID         uuid.UUID      `json:"id"`
	UserID     uuid.UUID      `json:"user_id"`
	MeasuredAt pgtype.Date    `json:"measured_at"`
	WeightKg   pgtype.Numeric `json:"weight_kg"`
	BodyFatPct pgtype.Numeric `json:"body_fat_pct"`
	CreatedAt  time.Time      `json:"created_at"`
}

type BodyPhoto struct {
	ID          uuid.UUID  `json:"id"`
	UserID      uuid.UUID  `json:"user_id"`
	StoragePath string     `json:"storage_path"`
	Kind        string     `json:"kind"`
	Analysis    []byte     `json:"analysis"`
	AnalyzedAt  *time.Time `json:"analyzed_at"`
	CreatedAt   time.Time  `json:"created_at"`
}

type Club struct {
	ID           uuid.UUID  `json:"id"`
	Name         string     `json:"name"`
	Description  *string    `json:"description"`
	OwnerID      uuid.UUID  `json:"owner_id"`
	InviteCode   string     `json:"invite_code"`
	TelegramLink *string    `json:"telegram_link"`
	CreatedAt    *time.Time `json:"created_at"`
}

type ClubMember struct {
	ID        uuid.UUID  `json:"id"`
	ClubID    uuid.UUID  `json:"club_id"`
	UserID    uuid.UUID  `json:"user_id"`
	Role      *string    `json:"role"`
	JoinedAt  *time.Time `json:"joined_at"`
	IsPrimary bool       `json:"is_primary"`
}

type CoachInviteCode struct {
	ID          uuid.UUID  `json:"id"`
	CoachID     uuid.UUID  `json:"coach_id"`
	SportTypeID int64      `json:"sport_type_id"`
	Code        string     `json:"code"`
	IsActive    bool       `json:"is_active"`
	ExpiresAt   *time.Time `json:"expires_at"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
}

type CoachingRelationship struct {
	ID          uuid.UUID  `json:"id"`
	CoachID     uuid.UUID  `json:"coach_id"`
	StudentID   uuid.UUID  `json:"student_id"`
	SportTypeID *int64     `json:"sport_type_id"`
	Status      *string    `json:"status"`
	CreatedAt   *time.Time `json:"created_at"`
}

type DailyPlan struct {
	ID          uuid.UUID   `json:"id"`
	UserID      *uuid.UUID  `json:"user_id"`
	Date        pgtype.Date `json:"date"`
	Content     string      `json:"content"`
	IsCompleted pgtype.Bool `json:"is_completed"`
	Feedback    *string     `json:"feedback"`
	CreatedAt   *time.Time  `json:"created_at"`
}

type Food struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Brand       *string        `json:"brand"`
	KcalPer100g pgtype.Numeric `json:"kcal_per_100g"`
	ProteinG    pgtype.Numeric `json:"protein_g"`
	CarbsG      pgtype.Numeric `json:"carbs_g"`
	FatG        pgtype.Numeric `json:"fat_g"`
	Source      string         `json:"source"`
	CreatedBy   *uuid.UUID     `json:"created_by"`
	CreatedAt   time.Time      `json:"created_at"`
	SugarG      pgtype.Numeric `json:"sugar_g"`
	FiberG      pgtype.Numeric `json:"fiber_g"`
	SodiumMg    pgtype.Numeric `json:"sodium_mg"`
	FdcID       pgtype.Int4    `json:"fdc_id"`
}

type Goal struct {
	ID          uuid.UUID      `json:"id"`
	UserID      uuid.UUID      `json:"user_id"`
	GoalType    string         `json:"goal_type"`
	TargetValue pgtype.Numeric `json:"target_value"`
	StartValue  pgtype.Numeric `json:"start_value"`
	TargetDate  pgtype.Date    `json:"target_date"`
	Status      string         `json:"status"`
	AchievedAt  *time.Time     `json:"achieved_at"`
	CreatedAt   time.Time      `json:"created_at"`
}

type GroupDay struct {
	GroupID    uuid.UUID   `json:"group_id"`
	Date       pgtype.Date `json:"date"`
	AllTrained bool        `json:"all_trained"`
}

type GroupMember struct {
	GroupID  uuid.UUID `json:"group_id"`
	UserID   uuid.UUID `json:"user_id"`
	JoinedAt time.Time `json:"joined_at"`
}

type Log struct {
	ID          uuid.UUID   `json:"id"`
	UserID      *uuid.UUID  `json:"user_id"`
	Date        pgtype.Date `json:"date"`
	SportTypeID *int64      `json:"sport_type_id"`
	Status      LogStatus   `json:"status"`
	Notes       *string     `json:"notes"`
	CreatedAt   *time.Time  `json:"created_at"`
	PlanItemID  *uuid.UUID  `json:"plan_item_id"`
}

type MealLog struct {
	ID            uuid.UUID      `json:"id"`
	UserID        uuid.UUID      `json:"user_id"`
	Date          pgtype.Date    `json:"date"`
	MealType      string         `json:"meal_type"`
	FoodID        *uuid.UUID     `json:"food_id"`
	FreeText      *string        `json:"free_text"`
	QuantityG     pgtype.Numeric `json:"quantity_g"`
	Kcal          pgtype.Numeric `json:"kcal"`
	ProteinG      pgtype.Numeric `json:"protein_g"`
	CarbsG        pgtype.Numeric `json:"carbs_g"`
	FatG          pgtype.Numeric `json:"fat_g"`
	EntryMethod   string         `json:"entry_method"`
	PhotoEstimate []byte         `json:"photo_estimate"`
	CreatedAt     time.Time      `json:"created_at"`
	SugarG        pgtype.Numeric `json:"sugar_g"`
	FiberG        pgtype.Numeric `json:"fiber_g"`
	SodiumMg      pgtype.Numeric `json:"sodium_mg"`
}

type MealPlan struct {
	ID             uuid.UUID      `json:"id"`
	UserID         uuid.UUID      `json:"user_id"`
	Status         string         `json:"status"`
	Intake         []byte         `json:"intake"`
	KcalTarget     pgtype.Numeric `json:"kcal_target"`
	ProteinGTarget pgtype.Numeric `json:"protein_g_target"`
	CarbsGTarget   pgtype.Numeric `json:"carbs_g_target"`
	FatGTarget     pgtype.Numeric `json:"fat_g_target"`
	CreatedAt      time.Time      `json:"created_at"`
}

type MealPlanItem struct {
	ID          uuid.UUID      `json:"id"`
	PlanID      uuid.UUID      `json:"plan_id"`
	UserID      uuid.UUID      `json:"user_id"`
	DayOfWeek   int32          `json:"day_of_week"`
	MealType    string         `json:"meal_type"`
	Title       string         `json:"title"`
	Ingredients []byte         `json:"ingredients"`
	Recipe      *string        `json:"recipe"`
	VideoQuery  *string        `json:"video_query"`
	Kcal        pgtype.Numeric `json:"kcal"`
	ProteinG    pgtype.Numeric `json:"protein_g"`
	CarbsG      pgtype.Numeric `json:"carbs_g"`
	FatG        pgtype.Numeric `json:"fat_g"`
	SugarG      pgtype.Numeric `json:"sugar_g"`
	FiberG      pgtype.Numeric `json:"fiber_g"`
	SodiumMg    pgtype.Numeric `json:"sodium_mg"`
	Sort        int32          `json:"sort"`
}

type PlanItem struct {
	ID          uuid.UUID `json:"id"`
	PlanID      uuid.UUID `json:"plan_id"`
	Week        int32     `json:"week"`
	DayOfWeek   int16     `json:"day_of_week"`
	ItemType    string    `json:"item_type"`
	Title       string    `json:"title"`
	Details     []byte    `json:"details"`
	IsCompleted bool      `json:"is_completed"`
	Description *string   `json:"description"`
}

type Profile struct {
	ID                      uuid.UUID      `json:"id"`
	Email                   *string        `json:"email"`
	Role                    *string        `json:"role"`
	Xp                      pgtype.Int4    `json:"xp"`
	Level                   pgtype.Int4    `json:"level"`
	Hearts                  pgtype.Int4    `json:"hearts"`
	CurrentStreak           pgtype.Int4    `json:"current_streak"`
	BestStreak              pgtype.Int4    `json:"best_streak"`
	LeagueTier              *string        `json:"league_tier"`
	FullName                *string        `json:"full_name"`
	AvatarUrl               *string        `json:"avatar_url"`
	BirthDate               pgtype.Date    `json:"birth_date"`
	Sex                     *string        `json:"sex"`
	HeightCm                pgtype.Numeric `json:"height_cm"`
	WeightKg                pgtype.Numeric `json:"weight_kg"`
	BodyFatPct              pgtype.Numeric `json:"body_fat_pct"`
	TrainingHistory         *string        `json:"training_history"`
	PreferredUnits          string         `json:"preferred_units"`
	AiPhotoConsentAt        *time.Time     `json:"ai_photo_consent_at"`
	StreakEvaluatedDate     pgtype.Date    `json:"streak_evaluated_date"`
	NutritionSharingEnabled bool           `json:"nutrition_sharing_enabled"`
	Country                 *string        `json:"country"`
}

type ProfileCard struct {
	ID         uuid.UUID   `json:"id"`
	FullName   *string     `json:"full_name"`
	AvatarUrl  *string     `json:"avatar_url"`
	Xp         pgtype.Int4 `json:"xp"`
	Level      pgtype.Int4 `json:"level"`
	LeagueTier *string     `json:"league_tier"`
}

type Schedule struct {
	ID          uuid.UUID   `json:"id"`
	UserID      *uuid.UUID  `json:"user_id"`
	DayOfWeek   int16       `json:"day_of_week"`
	SportTypeID *int64      `json:"sport_type_id"`
	Time        pgtype.Time `json:"time"`
	CreatedAt   *time.Time  `json:"created_at"`
	StartsOn    pgtype.Date `json:"starts_on"`
	EndsOn      pgtype.Date `json:"ends_on"`
}

type SessionLog struct {
	ID         uuid.UUID   `json:"id"`
	UserID     uuid.UUID   `json:"user_id"`
	PlanItemID uuid.UUID   `json:"plan_item_id"`
	Sport      string      `json:"sport"`
	Rpe        pgtype.Int4 `json:"rpe"`
	Actual     []byte      `json:"actual"`
	Note       *string     `json:"note"`
	AiFeedback []byte      `json:"ai_feedback"`
	CreatedAt  time.Time   `json:"created_at"`
}

type SocialGraph struct {
	ID          uuid.UUID  `json:"id"`
	FollowerID  *uuid.UUID `json:"follower_id"`
	FollowingID *uuid.UUID `json:"following_id"`
	CreatedAt   *time.Time `json:"created_at"`
}

type SportType struct {
	ID           int64     `json:"id"`
	CreatedAt    time.Time `json:"created_at"`
	Name         *string   `json:"name"`
	XpMultiplier *float32  `json:"xp_multiplier"`
}

type Supplement struct {
	ID           uuid.UUID `json:"id"`
	UserID       uuid.UUID `json:"user_id"`
	Name         string    `json:"name"`
	Dose         *string   `json:"dose"`
	CreatedAt    time.Time `json:"created_at"`
	ScheduleType string    `json:"schedule_type"`
	DaysOfWeek   []int16   `json:"days_of_week"`
}

type SupplementLog struct {
	ID           uuid.UUID   `json:"id"`
	UserID       uuid.UUID   `json:"user_id"`
	SupplementID uuid.UUID   `json:"supplement_id"`
	Date         pgtype.Date `json:"date"`
	CreatedAt    time.Time   `json:"created_at"`
}

type TrainingGroup struct {
	ID                uuid.UUID   `json:"id"`
	Name              string      `json:"name"`
	InviteCode        string      `json:"invite_code"`
	CreatedBy         uuid.UUID   `json:"created_by"`
	StreakCount       int32       `json:"streak_count"`
	BestStreak        int32       `json:"best_streak"`
	LastEvaluatedDate pgtype.Date `json:"last_evaluated_date"`
	CreatedAt         time.Time   `json:"created_at"`
}

type TrainingPlan struct {
	ID            uuid.UUID   `json:"id"`
	UserID        uuid.UUID   `json:"user_id"`
	RaceDate      pgtype.Date `json:"race_date"`
	GoalTime      *string     `json:"goal_time"`
	Status        string      `json:"status"`
	WeeksTotal    int32       `json:"weeks_total"`
	Summary       *string     `json:"summary"`
	Intake        []byte      `json:"intake"`
	RawAiResponse []byte      `json:"raw_ai_response"`
	Model         *string     `json:"model"`
	CreatedAt     time.Time   `json:"created_at"`
	PlanKind      string      `json:"plan_kind"`
	CreatedBy     *uuid.UUID  `json:"created_by"`
}

type User struct {
	ID              uuid.UUID   `json:"id"`
	Email           interface{} `json:"email"`
	PasswordHash    string      `json:"password_hash"`
	EmailVerifiedAt *time.Time  `json:"email_verified_at"`
	CreatedAt       time.Time   `json:"created_at"`
	UpdatedAt       time.Time   `json:"updated_at"`
}

type WeeklyCheckin struct {
	ID        uuid.UUID `json:"id"`
	PlanID    uuid.UUID `json:"plan_id"`
	Week      int32     `json:"week"`
	Scorecard []byte    `json:"scorecard"`
	Decision  string    `json:"decision"`
	Summary   *string   `json:"summary"`
	CreatedAt time.Time `json:"created_at"`
}

type WeeklyLeaderboard struct {
	UserID   *uuid.UUID `json:"user_id"`
	WeeklyXp int64      `json:"weekly_xp"`
}

type WeeklyQuota struct {
	ID              uuid.UUID `json:"id"`
	UserID          uuid.UUID `json:"user_id"`
	SportTypeID     int64     `json:"sport_type_id"`
	SessionsPerWeek int32     `json:"sessions_per_week"`
	CreatedAt       time.Time `json:"created_at"`
}

type XpTransaction struct {
	ID        uuid.UUID  `json:"id"`
	UserID    *uuid.UUID `json:"user_id"`
	Amount    int32      `json:"amount"`
	Reason    *string    `json:"reason"`
	CreatedAt *time.Time `json:"created_at"`
}
