// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: nutrition.sql

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const archiveMealPlans = `-- name: ArchiveMealPlans :execrows
UPDATE public.meal_plans SET status = 'archived' WHERE user_id = $1 AND status = 'active'
`

func (q *Queries) ArchiveMealPlans(ctx context.Context, userID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, archiveMealPlans, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countMealAwardsOn = `-- name: CountMealAwardsOn :one
SELECT count(*) AS awarded
FROM public.xp_transactions x
JOIN public.meal_logs m ON x.reason = 'meal_log:' || m.id::text
WHERE x.user_id = $1 AND m.user_id = $1
  AND m.date = CAST($2::text AS date)
`

type CountMealAwardsOnParams struct {
	UserID *uuid.UUID `json:"user_id"`
	OnDate string     `json:"on_date"`
}

// How many of the date's (remaining) meals hold a meal award — the 3-a-day cap.
func (q *Queries) CountMealAwardsOn(ctx context.Context, arg CountMealAwardsOnParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMealAwardsOn, arg.UserID, arg.OnDate)
	var awarded int64
	err := row.Scan(&awarded)
	return awarded, err
}

const countTrainingDays = `-- name: CountTrainingDays :one
SELECT count(DISTINCT day_of_week)::int AS days FROM public.schedules WHERE user_id = $1::uuid
`

// Distinct weekdays with a fixed session (any window), as the legacy planner counted.
func (q *Queries) CountTrainingDays(ctx context.Context, userID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countTrainingDays, userID)
	var days int32
	err := row.Scan(&days)
	return days, err
}

const dayIntake = `-- name: DayIntake :one
SELECT COALESCE(SUM(kcal), 0)::float8 AS kcal, count(*) AS meals
FROM public.meal_logs
WHERE user_id = $1 AND date = CAST($2::text AS date)
`

type DayIntakeParams struct {
	UserID uuid.UUID `json:"user_id"`
	OnDate string    `json:"on_date"`
}

type DayIntakeRow struct {
	Kcal  float64 `json:"kcal"`
	Meals int64   `json:"meals"`
}

func (q *Queries) DayIntake(ctx context.Context, arg DayIntakeParams) (DayIntakeRow, error) {
	row := q.db.QueryRow(ctx, dayIntake, arg.UserID, arg.OnDate)
	var i DayIntakeRow
	err := row.Scan(&i.Kcal, &i.Meals)
	return i, err
}

const deleteMealLog = `-- name: DeleteMealLog :execrows
DELETE FROM public.meal_logs WHERE id = $1 AND user_id = $2
`

type DeleteMealLogParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteMealLog(ctx context.Context, arg DeleteMealLogParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMealLog, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActiveMealPlan = `-- name: GetActiveMealPlan :one
SELECT id, kcal_target::float8 AS kcal_target, protein_g_target::float8 AS protein_g_target,
       carbs_g_target::float8 AS carbs_g_target, fat_g_target::float8 AS fat_g_target, intake
FROM public.meal_plans
WHERE user_id = $1 AND status = 'active'
ORDER BY created_at DESC
LIMIT 1
`

type GetActiveMealPlanRow struct {
	ID             uuid.UUID `json:"id"`
	KcalTarget     float64   `json:"kcal_target"`
	ProteinGTarget float64   `json:"protein_g_target"`
	CarbsGTarget   float64   `json:"carbs_g_target"`
	FatGTarget     float64   `json:"fat_g_target"`
	Intake         []byte    `json:"intake"`
}

func (q *Queries) GetActiveMealPlan(ctx context.Context, userID uuid.UUID) (GetActiveMealPlanRow, error) {
	row := q.db.QueryRow(ctx, getActiveMealPlan, userID)
	var i GetActiveMealPlanRow
	err := row.Scan(
		&i.ID,
		&i.KcalTarget,
		&i.ProteinGTarget,
		&i.CarbsGTarget,
		&i.FatGTarget,
		&i.Intake,
	)
	return i, err
}

const getFood = `-- name: GetFood :one
SELECT id, name, kcal_per_100g::float8 AS kcal_per_100g, protein_g::float8 AS protein_g, carbs_g::float8 AS carbs_g,
       fat_g::float8 AS fat_g, COALESCE(sugar_g, 0)::float8 AS sugar_g, COALESCE(fiber_g, 0)::float8 AS fiber_g,
       COALESCE(sodium_mg, 0)::float8 AS sodium_mg, source
FROM public.foods
WHERE id = $1
`

type GetFoodRow struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	KcalPer100g float64   `json:"kcal_per_100g"`
	ProteinG    float64   `json:"protein_g"`
	CarbsG      float64   `json:"carbs_g"`
	FatG        float64   `json:"fat_g"`
	SugarG      float64   `json:"sugar_g"`
	FiberG      float64   `json:"fiber_g"`
	SodiumMg    float64   `json:"sodium_mg"`
	Source      string    `json:"source"`
}

func (q *Queries) GetFood(ctx context.Context, id uuid.UUID) (GetFoodRow, error) {
	row := q.db.QueryRow(ctx, getFood, id)
	var i GetFoodRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.KcalPer100g,
		&i.ProteinG,
		&i.CarbsG,
		&i.FatG,
		&i.SugarG,
		&i.FiberG,
		&i.SodiumMg,
		&i.Source,
	)
	return i, err
}

const getFoodByFdcID = `-- name: GetFoodByFdcID :one
SELECT id, name, kcal_per_100g::float8 AS kcal_per_100g, protein_g::float8 AS protein_g, carbs_g::float8 AS carbs_g,
       fat_g::float8 AS fat_g, COALESCE(sugar_g, 0)::float8 AS sugar_g, COALESCE(fiber_g, 0)::float8 AS fiber_g,
       COALESCE(sodium_mg, 0)::float8 AS sodium_mg, source
FROM public.foods
WHERE fdc_id = $1::int
`

type GetFoodByFdcIDRow struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	KcalPer100g float64   `json:"kcal_per_100g"`
	ProteinG    float64   `json:"protein_g"`
	CarbsG      float64   `json:"carbs_g"`
	FatG        float64   `json:"fat_g"`
	SugarG      float64   `json:"sugar_g"`
	FiberG      float64   `json:"fiber_g"`
	SodiumMg    float64   `json:"sodium_mg"`
	Source      string    `json:"source"`
}

func (q *Queries) GetFoodByFdcID(ctx context.Context, fdcID int32) (GetFoodByFdcIDRow, error) {
	row := q.db.QueryRow(ctx, getFoodByFdcID, fdcID)
	var i GetFoodByFdcIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.KcalPer100g,
		&i.ProteinG,
		&i.CarbsG,
		&i.FatG,
		&i.SugarG,
		&i.FiberG,
		&i.SodiumMg,
		&i.Source,
	)
	return i, err
}

const hasActiveTrainingPlan = `-- name: HasActiveTrainingPlan :one
SELECT EXISTS (SELECT 1 FROM public.training_plans WHERE user_id = $1 AND status = 'active')
`

func (q *Queries) HasActiveTrainingPlan(ctx context.Context, userID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasActiveTrainingPlan, userID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertCalorieGoal = `-- name: InsertCalorieGoal :exec
INSERT INTO public.goals (user_id, goal_type, target_value, status)
VALUES ($1::uuid, 'calorie_intake', $2::float8, 'active')
`

type InsertCalorieGoalParams struct {
	UserID uuid.UUID `json:"user_id"`
	Kcal   float64   `json:"kcal"`
}

func (q *Queries) InsertCalorieGoal(ctx context.Context, arg InsertCalorieGoalParams) error {
	_, err := q.db.Exec(ctx, insertCalorieGoal, arg.UserID, arg.Kcal)
	return err
}

const insertMealLog = `-- name: InsertMealLog :one
INSERT INTO public.meal_logs (user_id, date, meal_type, food_id, free_text, quantity_g, kcal, protein_g, carbs_g, fat_g,
                              sugar_g, fiber_g, sodium_mg, entry_method, photo_estimate, created_at)
VALUES ($1::uuid, CAST($2::text AS date), $3::text, $4::uuid,
        $5::text, $6::float8, $7::float8, $8::float8,
        $9::float8, $10::float8, $11::float8, $12::float8,
        $13::float8, $14::text, $15::jsonb, clock_timestamp())
RETURNING id
`

type InsertMealLogParams struct {
	UserID        uuid.UUID     `json:"user_id"`
	OnDate        string        `json:"on_date"`
	MealType      string        `json:"meal_type"`
	FoodID        *uuid.UUID    `json:"food_id"`
	FreeText      string        `json:"free_text"`
	QuantityG     pgtype.Float8 `json:"quantity_g"`
	Kcal          float64       `json:"kcal"`
	ProteinG      float64       `json:"protein_g"`
	CarbsG        float64       `json:"carbs_g"`
	FatG          float64       `json:"fat_g"`
	SugarG        float64       `json:"sugar_g"`
	FiberG        float64       `json:"fiber_g"`
	SodiumMg      float64       `json:"sodium_mg"`
	EntryMethod   string        `json:"entry_method"`
	PhotoEstimate []byte        `json:"photo_estimate"`
}

// clock_timestamp keeps a batch (photo items) in its order.
func (q *Queries) InsertMealLog(ctx context.Context, arg InsertMealLogParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertMealLog,
		arg.UserID,
		arg.OnDate,
		arg.MealType,
		arg.FoodID,
		arg.FreeText,
		arg.QuantityG,
		arg.Kcal,
		arg.ProteinG,
		arg.CarbsG,
		arg.FatG,
		arg.SugarG,
		arg.FiberG,
		arg.SodiumMg,
		arg.EntryMethod,
		arg.PhotoEstimate,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertMealPlan = `-- name: InsertMealPlan :one
INSERT INTO public.meal_plans (user_id, status, intake, kcal_target, protein_g_target, carbs_g_target, fat_g_target)
VALUES ($1::uuid, 'active', $2::jsonb, $3::float8, $4::float8,
        $5::float8, $6::float8)
RETURNING id
`

type InsertMealPlanParams struct {
	UserID   uuid.UUID `json:"user_id"`
	Intake   []byte    `json:"intake"`
	Kcal     float64   `json:"kcal"`
	ProteinG float64   `json:"protein_g"`
	CarbsG   float64   `json:"carbs_g"`
	FatG     float64   `json:"fat_g"`
}

func (q *Queries) InsertMealPlan(ctx context.Context, arg InsertMealPlanParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertMealPlan,
		arg.UserID,
		arg.Intake,
		arg.Kcal,
		arg.ProteinG,
		arg.CarbsG,
		arg.FatG,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertMealPlanItem = `-- name: InsertMealPlanItem :exec
INSERT INTO public.meal_plan_items (plan_id, user_id, day_of_week, meal_type, title, ingredients, recipe, video_query,
                                    kcal, protein_g, carbs_g, fat_g, sugar_g, fiber_g, sodium_mg, sort)
VALUES ($1::uuid, $2::uuid, $3::int, $4::text,
        $5::text, $6::jsonb, $7::text, $8::text,
        $9::float8, $10::float8, $11::float8, $12::float8,
        $13::float8, $14::float8, $15::float8, $16::int)
`

type InsertMealPlanItemParams struct {
	PlanID      uuid.UUID `json:"plan_id"`
	UserID      uuid.UUID `json:"user_id"`
	DayOfWeek   int32     `json:"day_of_week"`
	MealType    string    `json:"meal_type"`
	Title       string    `json:"title"`
	Ingredients []byte    `json:"ingredients"`
	Recipe      string    `json:"recipe"`
	VideoQuery  string    `json:"video_query"`
	Kcal        float64   `json:"kcal"`
	ProteinG    float64   `json:"protein_g"`
	CarbsG      float64   `json:"carbs_g"`
	FatG        float64   `json:"fat_g"`
	SugarG      float64   `json:"sugar_g"`
	FiberG      float64   `json:"fiber_g"`
	SodiumMg    float64   `json:"sodium_mg"`
	Sort        int32     `json:"sort"`
}

func (q *Queries) InsertMealPlanItem(ctx context.Context, arg InsertMealPlanItemParams) error {
	_, err := q.db.Exec(ctx, insertMealPlanItem,
		arg.PlanID,
		arg.UserID,
		arg.DayOfWeek,
		arg.MealType,
		arg.Title,
		arg.Ingredients,
		arg.Recipe,
		arg.VideoQuery,
		arg.Kcal,
		arg.ProteinG,
		arg.CarbsG,
		arg.FatG,
		arg.SugarG,
		arg.FiberG,
		arg.SodiumMg,
		arg.Sort,
	)
	return err
}

const insertUSDAFood = `-- name: InsertUSDAFood :exec
INSERT INTO public.foods (name, kcal_per_100g, protein_g, carbs_g, fat_g, sugar_g, fiber_g, sodium_mg, source, created_by, fdc_id)
VALUES ($1::text, $2::float8, $3::float8, $4::float8,
        $5::float8, $6::float8, $7::float8, $8::float8,
        'usda', $9::uuid, $10::int)
ON CONFLICT (fdc_id) WHERE fdc_id IS NOT NULL DO NOTHING
`

type InsertUSDAFoodParams struct {
	Name     string    `json:"name"`
	Kcal     float64   `json:"kcal"`
	ProteinG float64   `json:"protein_g"`
	CarbsG   float64   `json:"carbs_g"`
	FatG     float64   `json:"fat_g"`
	SugarG   float64   `json:"sugar_g"`
	FiberG   float64   `json:"fiber_g"`
	SodiumMg float64   `json:"sodium_mg"`
	UserID   uuid.UUID `json:"user_id"`
	FdcID    int32     `json:"fdc_id"`
}

// One shared row per USDA food; a second save of the same food is a no-op.
func (q *Queries) InsertUSDAFood(ctx context.Context, arg InsertUSDAFoodParams) error {
	_, err := q.db.Exec(ctx, insertUSDAFood,
		arg.Name,
		arg.Kcal,
		arg.ProteinG,
		arg.CarbsG,
		arg.FatG,
		arg.SugarG,
		arg.FiberG,
		arg.SodiumMg,
		arg.UserID,
		arg.FdcID,
	)
	return err
}

const ledgerHasReason = `-- name: LedgerHasReason :one
SELECT EXISTS (
  SELECT 1 FROM public.xp_transactions WHERE user_id = $1 AND reason = $2::text
)::bool AS awarded
`

type LedgerHasReasonParams struct {
	UserID *uuid.UUID `json:"user_id"`
	Reason string     `json:"reason"`
}

func (q *Queries) LedgerHasReason(ctx context.Context, arg LedgerHasReasonParams) (bool, error) {
	row := q.db.QueryRow(ctx, ledgerHasReason, arg.UserID, arg.Reason)
	var awarded bool
	err := row.Scan(&awarded)
	return awarded, err
}

const listMealNutrientsSince = `-- name: ListMealNutrientsSince :many
SELECT date::text AS date, kcal::float8 AS kcal, protein_g::float8 AS protein_g, carbs_g::float8 AS carbs_g,
       fat_g::float8 AS fat_g, sugar_g::float8 AS sugar_g, fiber_g::float8 AS fiber_g, sodium_mg::float8 AS sodium_mg
FROM public.meal_logs
WHERE user_id = $1::uuid AND date >= CAST($2::text AS date)
`

type ListMealNutrientsSinceParams struct {
	UserID   uuid.UUID `json:"user_id"`
	FromDate string    `json:"from_date"`
}

type ListMealNutrientsSinceRow struct {
	Date     string  `json:"date"`
	Kcal     float64 `json:"kcal"`
	ProteinG float64 `json:"protein_g"`
	CarbsG   float64 `json:"carbs_g"`
	FatG     float64 `json:"fat_g"`
	SugarG   float64 `json:"sugar_g"`
	FiberG   float64 `json:"fiber_g"`
	SodiumMg float64 `json:"sodium_mg"`
}

func (q *Queries) ListMealNutrientsSince(ctx context.Context, arg ListMealNutrientsSinceParams) ([]ListMealNutrientsSinceRow, error) {
	rows, err := q.db.Query(ctx, listMealNutrientsSince, arg.UserID, arg.FromDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMealNutrientsSinceRow{}
	for rows.Next() {
		var i ListMealNutrientsSinceRow
		if err := rows.Scan(
			&i.Date,
			&i.Kcal,
			&i.ProteinG,
			&i.CarbsG,
			&i.FatG,
			&i.SugarG,
			&i.FiberG,
			&i.SodiumMg,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMealPlanItems = `-- name: ListMealPlanItems :many
SELECT id, day_of_week, meal_type, title, ingredients, recipe, video_query, kcal::float8 AS kcal,
       protein_g::float8 AS protein_g, carbs_g::float8 AS carbs_g, fat_g::float8 AS fat_g,
       sugar_g::float8 AS sugar_g, fiber_g::float8 AS fiber_g, sodium_mg::float8 AS sodium_mg
FROM public.meal_plan_items
WHERE plan_id = $1 AND user_id = $2
ORDER BY day_of_week, sort, id
`

type ListMealPlanItemsParams struct {
	PlanID uuid.UUID `json:"plan_id"`
	UserID uuid.UUID `json:"user_id"`
}

type ListMealPlanItemsRow struct {
	ID          uuid.UUID `json:"id"`
	DayOfWeek   int32     `json:"day_of_week"`
	MealType    string    `json:"meal_type"`
	Title       string    `json:"title"`
	Ingredients []byte    `json:"ingredients"`
	Recipe      *string   `json:"recipe"`
	VideoQuery  *string   `json:"video_query"`
	Kcal        float64   `json:"kcal"`
	ProteinG    float64   `json:"protein_g"`
	CarbsG      float64   `json:"carbs_g"`
	FatG        float64   `json:"fat_g"`
	SugarG      float64   `json:"sugar_g"`
	FiberG      float64   `json:"fiber_g"`
	SodiumMg    float64   `json:"sodium_mg"`
}

func (q *Queries) ListMealPlanItems(ctx context.Context, arg ListMealPlanItemsParams) ([]ListMealPlanItemsRow, error) {
	rows, err := q.db.Query(ctx, listMealPlanItems, arg.PlanID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMealPlanItemsRow{}
	for rows.Next() {
		var i ListMealPlanItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.DayOfWeek,
			&i.MealType,
			&i.Title,
			&i.Ingredients,
			&i.Recipe,
			&i.VideoQuery,
			&i.Kcal,
			&i.ProteinG,
			&i.CarbsG,
			&i.FatG,
			&i.SugarG,
			&i.FiberG,
			&i.SodiumMg,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMealSlotsBetween = `-- name: ListMealSlotsBetween :many
SELECT date::text AS date, meal_type, kcal::float8 AS kcal
FROM public.meal_logs
WHERE user_id = $1::uuid
  AND date BETWEEN CAST($2::text AS date) AND CAST($3::text AS date)
`

type ListMealSlotsBetweenParams struct {
	UserID   uuid.UUID `json:"user_id"`
	FromDate string    `json:"from_date"`
	ToDate   string    `json:"to_date"`
}

type ListMealSlotsBetweenRow struct {
	Date     string  `json:"date"`
	MealType string  `json:"meal_type"`
	Kcal     float64 `json:"kcal"`
}

func (q *Queries) ListMealSlotsBetween(ctx context.Context, arg ListMealSlotsBetweenParams) ([]ListMealSlotsBetweenRow, error) {
	rows, err := q.db.Query(ctx, listMealSlotsBetween, arg.UserID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMealSlotsBetweenRow{}
	for rows.Next() {
		var i ListMealSlotsBetweenRow
		if err := rows.Scan(&i.Date, &i.MealType, &i.Kcal); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMealsOn = `-- name: ListMealsOn :many

SELECT id, meal_type, free_text, quantity_g, kcal::float8 AS kcal,
       protein_g::float8 AS protein_g, carbs_g::float8 AS carbs_g, fat_g::float8 AS fat_g,
       sugar_g::float8 AS sugar_g, fiber_g::float8 AS fiber_g, sodium_mg::float8 AS sodium_mg, entry_method
FROM public.meal_logs
WHERE user_id = $1::uuid AND date = CAST($2::text AS date)
ORDER BY created_at, id
`

type ListMealsOnParams struct {
	UserID uuid.UUID `json:"user_id"`
	OnDate string    `json:"on_date"`
}

type ListMealsOnRow struct {
	ID          uuid.UUID      `json:"id"`
	MealType    string         `json:"meal_type"`
	FreeText    *string        `json:"free_text"`
	QuantityG   pgtype.Numeric `json:"quantity_g"`
	Kcal        float64        `json:"kcal"`
	ProteinG    float64        `json:"protein_g"`
	CarbsG      float64        `json:"carbs_g"`
	FatG        float64        `json:"fat_g"`
	SugarG      float64        `json:"sugar_g"`
	FiberG      float64        `json:"fiber_g"`
	SodiumMg    float64        `json:"sodium_mg"`
	EntryMethod string         `json:"entry_method"`
}

// Nutrition: meal logs, foods, and meal XP.
// Run with the coachin_app pool inside store.WithUser.
func (q *Queries) ListMealsOn(ctx context.Context, arg ListMealsOnParams) ([]ListMealsOnRow, error) {
	rows, err := q.db.Query(ctx, listMealsOn, arg.UserID, arg.OnDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMealsOnRow{}
	for rows.Next() {
		var i ListMealsOnRow
		if err := rows.Scan(
			&i.ID,
			&i.MealType,
			&i.FreeText,
			&i.QuantityG,
			&i.Kcal,
			&i.ProteinG,
			&i.CarbsG,
			&i.FatG,
			&i.SugarG,
			&i.FiberG,
			&i.SodiumMg,
			&i.EntryMethod,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mealPlanProfile = `-- name: MealPlanProfile :one
SELECT sex, birth_date, height_cm, weight_kg, country FROM public.profiles WHERE id = $1
`

type MealPlanProfileRow struct {
	Sex       *string        `json:"sex"`
	BirthDate pgtype.Date    `json:"birth_date"`
	HeightCm  pgtype.Numeric `json:"height_cm"`
	WeightKg  pgtype.Numeric `json:"weight_kg"`
	Country   *string        `json:"country"`
}

func (q *Queries) MealPlanProfile(ctx context.Context, id uuid.UUID) (MealPlanProfileRow, error) {
	row := q.db.QueryRow(ctx, mealPlanProfile, id)
	var i MealPlanProfileRow
	err := row.Scan(
		&i.Sex,
		&i.BirthDate,
		&i.HeightCm,
		&i.WeightKg,
		&i.Country,
	)
	return i, err
}

const mealXPOutstanding = `-- name: MealXPOutstanding :one
SELECT COALESCE(SUM(amount), 0)::int AS xp
FROM public.xp_transactions
WHERE user_id = $1::uuid
  AND reason IN ('meal_log:' || $2::text, 'meal_log_undo:' || $2::text)
`

type MealXPOutstandingParams struct {
	UserID    uuid.UUID `json:"user_id"`
	MealLogID string    `json:"meal_log_id"`
}

// XP a meal log earned and hasn't given back (0 or 5).
func (q *Queries) MealXPOutstanding(ctx context.Context, arg MealXPOutstandingParams) (int32, error) {
	row := q.db.QueryRow(ctx, mealXPOutstanding, arg.UserID, arg.MealLogID)
	var xp int32
	err := row.Scan(&xp)
	return xp, err
}

const profileCountry = `-- name: ProfileCountry :one
SELECT country FROM public.profiles WHERE id = $1
`

func (q *Queries) ProfileCountry(ctx context.Context, id uuid.UUID) (*string, error) {
	row := q.db.QueryRow(ctx, profileCountry, id)
	var country *string
	err := row.Scan(&country)
	return country, err
}

const searchFoods = `-- name: SearchFoods :many
SELECT id, name, kcal_per_100g::float8 AS kcal_per_100g, protein_g::float8 AS protein_g, carbs_g::float8 AS carbs_g,
       fat_g::float8 AS fat_g, COALESCE(sugar_g, 0)::float8 AS sugar_g, COALESCE(fiber_g, 0)::float8 AS fiber_g,
       COALESCE(sodium_mg, 0)::float8 AS sodium_mg, source
FROM public.foods
WHERE name ILIKE '%' || $1::text || '%' ESCAPE '\'
ORDER BY source, name, id
LIMIT 8
`

type SearchFoodsRow struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	KcalPer100g float64   `json:"kcal_per_100g"`
	ProteinG    float64   `json:"protein_g"`
	CarbsG      float64   `json:"carbs_g"`
	FatG        float64   `json:"fat_g"`
	SugarG      float64   `json:"sugar_g"`
	FiberG      float64   `json:"fiber_g"`
	SodiumMg    float64   `json:"sodium_mg"`
	Source      string    `json:"source"`
}

// Local food search, ordered by source as the legacy app (custom, seed, usda), then name.
func (q *Queries) SearchFoods(ctx context.Context, pattern string) ([]SearchFoodsRow, error) {
	rows, err := q.db.Query(ctx, searchFoods, pattern)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchFoodsRow{}
	for rows.Next() {
		var i SearchFoodsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.KcalPer100g,
			&i.ProteinG,
			&i.CarbsG,
			&i.FatG,
			&i.SugarG,
			&i.FiberG,
			&i.SodiumMg,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCalorieGoal = `-- name: UpdateCalorieGoal :execrows
UPDATE public.goals SET target_value = $1::float8
WHERE user_id = $2 AND goal_type = 'calorie_intake' AND status = 'active'
`

type UpdateCalorieGoalParams struct {
	Kcal   float64   `json:"kcal"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) UpdateCalorieGoal(ctx context.Context, arg UpdateCalorieGoalParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateCalorieGoal, arg.Kcal, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
