// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: nutrition.sql

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const awardDayAdherence = `-- name: AwardDayAdherence :one
SELECT public.award_day_adherence(CAST($1::text AS date))::text AS result
`

// Step A (ADR-5): +30 once for a past day within ±10% of the calorie goal (2+ meals).
func (q *Queries) AwardDayAdherence(ctx context.Context, onDate string) (string, error) {
	row := q.db.QueryRow(ctx, awardDayAdherence, onDate)
	var result string
	err := row.Scan(&result)
	return result, err
}

const awardMealXP = `-- name: AwardMealXP :one
SELECT public.award_meal_xp($1)::text AS result
`

// Step A (ADR-5): +5 once per log, at most 3 awarded logs per date.
func (q *Queries) AwardMealXP(ctx context.Context, mealLogID uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, awardMealXP, mealLogID)
	var result string
	err := row.Scan(&result)
	return result, err
}

const deleteMealLog = `-- name: DeleteMealLog :execrows
DELETE FROM public.meal_logs WHERE id = $1 AND user_id = $2
`

type DeleteMealLogParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteMealLog(ctx context.Context, arg DeleteMealLogParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMealLog, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getFood = `-- name: GetFood :one
SELECT id, name, kcal_per_100g::float8 AS kcal_per_100g, protein_g::float8 AS protein_g, carbs_g::float8 AS carbs_g,
       fat_g::float8 AS fat_g, COALESCE(sugar_g, 0)::float8 AS sugar_g, COALESCE(fiber_g, 0)::float8 AS fiber_g,
       COALESCE(sodium_mg, 0)::float8 AS sodium_mg, source
FROM public.foods
WHERE id = $1
`

type GetFoodRow struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	KcalPer100g float64   `json:"kcal_per_100g"`
	ProteinG    float64   `json:"protein_g"`
	CarbsG      float64   `json:"carbs_g"`
	FatG        float64   `json:"fat_g"`
	SugarG      float64   `json:"sugar_g"`
	FiberG      float64   `json:"fiber_g"`
	SodiumMg    float64   `json:"sodium_mg"`
	Source      string    `json:"source"`
}

func (q *Queries) GetFood(ctx context.Context, id uuid.UUID) (GetFoodRow, error) {
	row := q.db.QueryRow(ctx, getFood, id)
	var i GetFoodRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.KcalPer100g,
		&i.ProteinG,
		&i.CarbsG,
		&i.FatG,
		&i.SugarG,
		&i.FiberG,
		&i.SodiumMg,
		&i.Source,
	)
	return i, err
}

const getFoodByFdcID = `-- name: GetFoodByFdcID :one
SELECT id, name, kcal_per_100g::float8 AS kcal_per_100g, protein_g::float8 AS protein_g, carbs_g::float8 AS carbs_g,
       fat_g::float8 AS fat_g, COALESCE(sugar_g, 0)::float8 AS sugar_g, COALESCE(fiber_g, 0)::float8 AS fiber_g,
       COALESCE(sodium_mg, 0)::float8 AS sodium_mg, source
FROM public.foods
WHERE fdc_id = $1::int
`

type GetFoodByFdcIDRow struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	KcalPer100g float64   `json:"kcal_per_100g"`
	ProteinG    float64   `json:"protein_g"`
	CarbsG      float64   `json:"carbs_g"`
	FatG        float64   `json:"fat_g"`
	SugarG      float64   `json:"sugar_g"`
	FiberG      float64   `json:"fiber_g"`
	SodiumMg    float64   `json:"sodium_mg"`
	Source      string    `json:"source"`
}

func (q *Queries) GetFoodByFdcID(ctx context.Context, fdcID int32) (GetFoodByFdcIDRow, error) {
	row := q.db.QueryRow(ctx, getFoodByFdcID, fdcID)
	var i GetFoodByFdcIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.KcalPer100g,
		&i.ProteinG,
		&i.CarbsG,
		&i.FatG,
		&i.SugarG,
		&i.FiberG,
		&i.SodiumMg,
		&i.Source,
	)
	return i, err
}

const insertMealLog = `-- name: InsertMealLog :one
INSERT INTO public.meal_logs (user_id, date, meal_type, food_id, free_text, quantity_g, kcal, protein_g, carbs_g, fat_g,
                              sugar_g, fiber_g, sodium_mg, entry_method, photo_estimate, created_at)
VALUES ($1::uuid, CAST($2::text AS date), $3::text, $4::uuid,
        $5::text, $6::float8, $7::float8, $8::float8,
        $9::float8, $10::float8, $11::float8, $12::float8,
        $13::float8, $14::text, $15::jsonb, clock_timestamp())
RETURNING id
`

type InsertMealLogParams struct {
	UserID        uuid.UUID     `json:"user_id"`
	OnDate        string        `json:"on_date"`
	MealType      string        `json:"meal_type"`
	FoodID        *uuid.UUID    `json:"food_id"`
	FreeText      string        `json:"free_text"`
	QuantityG     pgtype.Float8 `json:"quantity_g"`
	Kcal          float64       `json:"kcal"`
	ProteinG      float64       `json:"protein_g"`
	CarbsG        float64       `json:"carbs_g"`
	FatG          float64       `json:"fat_g"`
	SugarG        float64       `json:"sugar_g"`
	FiberG        float64       `json:"fiber_g"`
	SodiumMg      float64       `json:"sodium_mg"`
	EntryMethod   string        `json:"entry_method"`
	PhotoEstimate []byte        `json:"photo_estimate"`
}

// clock_timestamp keeps a batch (photo items) in its order.
func (q *Queries) InsertMealLog(ctx context.Context, arg InsertMealLogParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertMealLog,
		arg.UserID,
		arg.OnDate,
		arg.MealType,
		arg.FoodID,
		arg.FreeText,
		arg.QuantityG,
		arg.Kcal,
		arg.ProteinG,
		arg.CarbsG,
		arg.FatG,
		arg.SugarG,
		arg.FiberG,
		arg.SodiumMg,
		arg.EntryMethod,
		arg.PhotoEstimate,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertUSDAFood = `-- name: InsertUSDAFood :exec
INSERT INTO public.foods (name, kcal_per_100g, protein_g, carbs_g, fat_g, sugar_g, fiber_g, sodium_mg, source, created_by, fdc_id)
VALUES ($1::text, $2::float8, $3::float8, $4::float8,
        $5::float8, $6::float8, $7::float8, $8::float8,
        'usda', $9::uuid, $10::int)
ON CONFLICT (fdc_id) WHERE fdc_id IS NOT NULL DO NOTHING
`

type InsertUSDAFoodParams struct {
	Name     string    `json:"name"`
	Kcal     float64   `json:"kcal"`
	ProteinG float64   `json:"protein_g"`
	CarbsG   float64   `json:"carbs_g"`
	FatG     float64   `json:"fat_g"`
	SugarG   float64   `json:"sugar_g"`
	FiberG   float64   `json:"fiber_g"`
	SodiumMg float64   `json:"sodium_mg"`
	UserID   uuid.UUID `json:"user_id"`
	FdcID    int32     `json:"fdc_id"`
}

// One shared row per USDA food; a second save of the same food is a no-op.
func (q *Queries) InsertUSDAFood(ctx context.Context, arg InsertUSDAFoodParams) error {
	_, err := q.db.Exec(ctx, insertUSDAFood,
		arg.Name,
		arg.Kcal,
		arg.ProteinG,
		arg.CarbsG,
		arg.FatG,
		arg.SugarG,
		arg.FiberG,
		arg.SodiumMg,
		arg.UserID,
		arg.FdcID,
	)
	return err
}

const listMealNutrientsSince = `-- name: ListMealNutrientsSince :many
SELECT date::text AS date, kcal::float8 AS kcal, protein_g::float8 AS protein_g, carbs_g::float8 AS carbs_g,
       fat_g::float8 AS fat_g, sugar_g::float8 AS sugar_g, fiber_g::float8 AS fiber_g, sodium_mg::float8 AS sodium_mg
FROM public.meal_logs
WHERE user_id = $1::uuid AND date >= CAST($2::text AS date)
`

type ListMealNutrientsSinceParams struct {
	UserID   uuid.UUID `json:"user_id"`
	FromDate string    `json:"from_date"`
}

type ListMealNutrientsSinceRow struct {
	Date     string  `json:"date"`
	Kcal     float64 `json:"kcal"`
	ProteinG float64 `json:"protein_g"`
	CarbsG   float64 `json:"carbs_g"`
	FatG     float64 `json:"fat_g"`
	SugarG   float64 `json:"sugar_g"`
	FiberG   float64 `json:"fiber_g"`
	SodiumMg float64 `json:"sodium_mg"`
}

func (q *Queries) ListMealNutrientsSince(ctx context.Context, arg ListMealNutrientsSinceParams) ([]ListMealNutrientsSinceRow, error) {
	rows, err := q.db.Query(ctx, listMealNutrientsSince, arg.UserID, arg.FromDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMealNutrientsSinceRow{}
	for rows.Next() {
		var i ListMealNutrientsSinceRow
		if err := rows.Scan(
			&i.Date,
			&i.Kcal,
			&i.ProteinG,
			&i.CarbsG,
			&i.FatG,
			&i.SugarG,
			&i.FiberG,
			&i.SodiumMg,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMealsOn = `-- name: ListMealsOn :many

SELECT id, meal_type, free_text, quantity_g, kcal::float8 AS kcal,
       protein_g::float8 AS protein_g, carbs_g::float8 AS carbs_g, fat_g::float8 AS fat_g,
       sugar_g::float8 AS sugar_g, fiber_g::float8 AS fiber_g, sodium_mg::float8 AS sodium_mg, entry_method
FROM public.meal_logs
WHERE user_id = $1::uuid AND date = CAST($2::text AS date)
ORDER BY created_at, id
`

type ListMealsOnParams struct {
	UserID uuid.UUID `json:"user_id"`
	OnDate string    `json:"on_date"`
}

type ListMealsOnRow struct {
	ID          uuid.UUID      `json:"id"`
	MealType    string         `json:"meal_type"`
	FreeText    *string        `json:"free_text"`
	QuantityG   pgtype.Numeric `json:"quantity_g"`
	Kcal        float64        `json:"kcal"`
	ProteinG    float64        `json:"protein_g"`
	CarbsG      float64        `json:"carbs_g"`
	FatG        float64        `json:"fat_g"`
	SugarG      float64        `json:"sugar_g"`
	FiberG      float64        `json:"fiber_g"`
	SodiumMg    float64        `json:"sodium_mg"`
	EntryMethod string         `json:"entry_method"`
}

// Nutrition: meal logs, foods, and meal XP.
// Run with the coachin_app pool inside store.WithUser.
func (q *Queries) ListMealsOn(ctx context.Context, arg ListMealsOnParams) ([]ListMealsOnRow, error) {
	rows, err := q.db.Query(ctx, listMealsOn, arg.UserID, arg.OnDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMealsOnRow{}
	for rows.Next() {
		var i ListMealsOnRow
		if err := rows.Scan(
			&i.ID,
			&i.MealType,
			&i.FreeText,
			&i.QuantityG,
			&i.Kcal,
			&i.ProteinG,
			&i.CarbsG,
			&i.FatG,
			&i.SugarG,
			&i.FiberG,
			&i.SodiumMg,
			&i.EntryMethod,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mealXPOutstanding = `-- name: MealXPOutstanding :one
SELECT COALESCE(SUM(amount), 0)::int AS xp
FROM public.xp_transactions
WHERE user_id = $1::uuid
  AND reason IN ('meal_log:' || $2::text, 'meal_log_undo:' || $2::text)
`

type MealXPOutstandingParams struct {
	UserID    uuid.UUID `json:"user_id"`
	MealLogID string    `json:"meal_log_id"`
}

// XP a meal log earned and hasn't given back (0 or 5).
func (q *Queries) MealXPOutstanding(ctx context.Context, arg MealXPOutstandingParams) (int32, error) {
	row := q.db.QueryRow(ctx, mealXPOutstanding, arg.UserID, arg.MealLogID)
	var xp int32
	err := row.Scan(&xp)
	return xp, err
}

const searchFoods = `-- name: SearchFoods :many
SELECT id, name, kcal_per_100g::float8 AS kcal_per_100g, protein_g::float8 AS protein_g, carbs_g::float8 AS carbs_g,
       fat_g::float8 AS fat_g, COALESCE(sugar_g, 0)::float8 AS sugar_g, COALESCE(fiber_g, 0)::float8 AS fiber_g,
       COALESCE(sodium_mg, 0)::float8 AS sodium_mg, source
FROM public.foods
WHERE name ILIKE '%' || $1::text || '%' ESCAPE '\'
ORDER BY source, name, id
LIMIT 8
`

type SearchFoodsRow struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	KcalPer100g float64   `json:"kcal_per_100g"`
	ProteinG    float64   `json:"protein_g"`
	CarbsG      float64   `json:"carbs_g"`
	FatG        float64   `json:"fat_g"`
	SugarG      float64   `json:"sugar_g"`
	FiberG      float64   `json:"fiber_g"`
	SodiumMg    float64   `json:"sodium_mg"`
	Source      string    `json:"source"`
}

// Local food search, ordered by source as the legacy app (custom, seed, usda), then name.
func (q *Queries) SearchFoods(ctx context.Context, pattern string) ([]SearchFoodsRow, error) {
	rows, err := q.db.Query(ctx, searchFoods, pattern)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchFoodsRow{}
	for rows.Next() {
		var i SearchFoodsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.KcalPer100g,
			&i.ProteinG,
			&i.CarbsG,
			&i.FatG,
			&i.SugarG,
			&i.FiberG,
			&i.SodiumMg,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
