// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: photos.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countPhotosByKind = `-- name: CountPhotosByKind :many
SELECT kind, count(*)::int AS n FROM public.body_photos WHERE user_id = $1 GROUP BY kind
`

type CountPhotosByKindRow struct {
	Kind string `json:"kind"`
	N    int32  `json:"n"`
}

func (q *Queries) CountPhotosByKind(ctx context.Context, userID uuid.UUID) ([]CountPhotosByKindRow, error) {
	rows, err := q.db.Query(ctx, countPhotosByKind, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountPhotosByKindRow{}
	for rows.Next() {
		var i CountPhotosByKindRow
		if err := rows.Scan(&i.Kind, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deletePhoto = `-- name: DeletePhoto :one
DELETE FROM public.body_photos WHERE id = $1 AND user_id = $2
RETURNING storage_path
`

type DeletePhotoParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeletePhoto(ctx context.Context, arg DeletePhotoParams) (string, error) {
	row := q.db.QueryRow(ctx, deletePhoto, arg.ID, arg.UserID)
	var storage_path string
	err := row.Scan(&storage_path)
	return storage_path, err
}

const insertPhotoUnderCap = `-- name: InsertPhotoUnderCap :one
INSERT INTO public.body_photos (user_id, storage_path, kind)
SELECT $1::uuid, $2::text, $3::text
WHERE (SELECT count(*) FROM public.body_photos WHERE user_id = $1::uuid AND kind = $3::text) < $4::int
RETURNING id
`

type InsertPhotoUnderCapParams struct {
	UserID      uuid.UUID `json:"user_id"`
	StoragePath string    `json:"storage_path"`
	Kind        string    `json:"kind"`
	MaxCount    int32     `json:"max_count"`
}

// Inserts only while the user has fewer than max_count of that kind (the
// caller holds the profile lock, so concurrent uploads can't both pass).
func (q *Queries) InsertPhotoUnderCap(ctx context.Context, arg InsertPhotoUnderCapParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertPhotoUnderCap,
		arg.UserID,
		arg.StoragePath,
		arg.Kind,
		arg.MaxCount,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listPhotos = `-- name: ListPhotos :many
SELECT id, kind, created_at, analysis, analyzed_at FROM public.body_photos
WHERE user_id = $1
ORDER BY created_at DESC
`

type ListPhotosRow struct {
	ID         uuid.UUID  `json:"id"`
	Kind       string     `json:"kind"`
	CreatedAt  time.Time  `json:"created_at"`
	Analysis   []byte     `json:"analysis"`
	AnalyzedAt *time.Time `json:"analyzed_at"`
}

func (q *Queries) ListPhotos(ctx context.Context, userID uuid.UUID) ([]ListPhotosRow, error) {
	rows, err := q.db.Query(ctx, listPhotos, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPhotosRow{}
	for rows.Next() {
		var i ListPhotosRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.CreatedAt,
			&i.Analysis,
			&i.AnalyzedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const photoPath = `-- name: PhotoPath :one
SELECT storage_path FROM public.body_photos WHERE id = $1 AND user_id = $2
`

type PhotoPathParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) PhotoPath(ctx context.Context, arg PhotoPathParams) (string, error) {
	row := q.db.QueryRow(ctx, photoPath, arg.ID, arg.UserID)
	var storage_path string
	err := row.Scan(&storage_path)
	return storage_path, err
}
