// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profile.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const abandonGoal = `-- name: AbandonGoal :execrows
UPDATE public.goals SET status = 'abandoned'
WHERE id = $1 AND user_id = $2 AND status = 'active'
`

type AbandonGoalParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) AbandonGoal(ctx context.Context, arg AbandonGoalParams) (int64, error) {
	result, err := q.db.Exec(ctx, abandonGoal, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteMeasurement = `-- name: DeleteMeasurement :execrows
DELETE FROM public.body_measurements WHERE id = $1 AND user_id = $2
`

type DeleteMeasurementParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteMeasurement(ctx context.Context, arg DeleteMeasurementParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMeasurement, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBodyProfile = `-- name: GetBodyProfile :one
SELECT birth_date, sex, height_cm, training_history, country, weight_kg, body_fat_pct, nutrition_sharing_enabled
FROM public.profiles WHERE id = $1
`

type GetBodyProfileRow struct {
	BirthDate               pgtype.Date    `json:"birth_date"`
	Sex                     *string        `json:"sex"`
	HeightCm                pgtype.Numeric `json:"height_cm"`
	TrainingHistory         *string        `json:"training_history"`
	Country                 *string        `json:"country"`
	WeightKg                pgtype.Numeric `json:"weight_kg"`
	BodyFatPct              pgtype.Numeric `json:"body_fat_pct"`
	NutritionSharingEnabled bool           `json:"nutrition_sharing_enabled"`
}

func (q *Queries) GetBodyProfile(ctx context.Context, userID uuid.UUID) (GetBodyProfileRow, error) {
	row := q.db.QueryRow(ctx, getBodyProfile, userID)
	var i GetBodyProfileRow
	err := row.Scan(
		&i.BirthDate,
		&i.Sex,
		&i.HeightCm,
		&i.TrainingHistory,
		&i.Country,
		&i.WeightKg,
		&i.BodyFatPct,
		&i.NutritionSharingEnabled,
	)
	return i, err
}

const insertGoal = `-- name: InsertGoal :exec
INSERT INTO public.goals (user_id, goal_type, target_value, start_value, target_date)
VALUES ($1, $2::text, $3::float8, $4::float8,
        CAST($5::text AS date))
`

type InsertGoalParams struct {
	UserID      uuid.UUID     `json:"user_id"`
	GoalType    string        `json:"goal_type"`
	TargetValue float64       `json:"target_value"`
	StartValue  pgtype.Float8 `json:"start_value"`
	TargetDate  *string       `json:"target_date"`
}

func (q *Queries) InsertGoal(ctx context.Context, arg InsertGoalParams) error {
	_, err := q.db.Exec(ctx, insertGoal,
		arg.UserID,
		arg.GoalType,
		arg.TargetValue,
		arg.StartValue,
		arg.TargetDate,
	)
	return err
}

const insertMeasurement = `-- name: InsertMeasurement :exec
INSERT INTO public.body_measurements (user_id, weight_kg, body_fat_pct)
VALUES ($1, $2::float8, $3::float8)
`

type InsertMeasurementParams struct {
	UserID     uuid.UUID     `json:"user_id"`
	WeightKg   pgtype.Float8 `json:"weight_kg"`
	BodyFatPct pgtype.Float8 `json:"body_fat_pct"`
}

func (q *Queries) InsertMeasurement(ctx context.Context, arg InsertMeasurementParams) error {
	_, err := q.db.Exec(ctx, insertMeasurement, arg.UserID, arg.WeightKg, arg.BodyFatPct)
	return err
}

const kcalOn = `-- name: KcalOn :one
SELECT COALESCE(sum(kcal), 0)::float8 AS kcal FROM public.meal_logs
WHERE user_id = $1 AND date = CAST($2::text AS date)
`

type KcalOnParams struct {
	UserID uuid.UUID `json:"user_id"`
	OnDate string    `json:"on_date"`
}

func (q *Queries) KcalOn(ctx context.Context, arg KcalOnParams) (float64, error) {
	row := q.db.QueryRow(ctx, kcalOn, arg.UserID, arg.OnDate)
	var kcal float64
	err := row.Scan(&kcal)
	return kcal, err
}

const latestMeasurementValues = `-- name: LatestMeasurementValues :one
SELECT
  COALESCE((SELECT m.weight_kg FROM (SELECT weight_kg, measured_at, created_at FROM public.body_measurements bm
             WHERE bm.user_id = p.id ORDER BY measured_at DESC, created_at DESC LIMIT 10) m
            WHERE m.weight_kg IS NOT NULL ORDER BY m.measured_at DESC, m.created_at DESC LIMIT 1), p.weight_kg) AS weight_kg,
  COALESCE((SELECT m.body_fat_pct FROM (SELECT body_fat_pct, measured_at, created_at FROM public.body_measurements bm
             WHERE bm.user_id = p.id ORDER BY measured_at DESC, created_at DESC LIMIT 10) m
            WHERE m.body_fat_pct IS NOT NULL ORDER BY m.measured_at DESC, m.created_at DESC LIMIT 1), p.body_fat_pct) AS body_fat_pct
FROM public.profiles p WHERE p.id = $1
`

type LatestMeasurementValuesRow struct {
	WeightKg   pgtype.Numeric `json:"weight_kg"`
	BodyFatPct pgtype.Numeric `json:"body_fat_pct"`
}

// The newest non-null weight / body fat among the last 10 readings, falling
// back to the profile snapshot (legacy getGoalsWithProgress).
func (q *Queries) LatestMeasurementValues(ctx context.Context, userID uuid.UUID) (LatestMeasurementValuesRow, error) {
	row := q.db.QueryRow(ctx, latestMeasurementValues, userID)
	var i LatestMeasurementValuesRow
	err := row.Scan(&i.WeightKg, &i.BodyFatPct)
	return i, err
}

const listGoals = `-- name: ListGoals :many
SELECT id, goal_type, target_value, start_value, target_date, status, achieved_at, created_at
FROM public.goals
WHERE user_id = $1
ORDER BY created_at DESC
`

type ListGoalsRow struct {
	ID          uuid.UUID      `json:"id"`
	GoalType    string         `json:"goal_type"`
	TargetValue pgtype.Numeric `json:"target_value"`
	StartValue  pgtype.Numeric `json:"start_value"`
	TargetDate  pgtype.Date    `json:"target_date"`
	Status      string         `json:"status"`
	AchievedAt  *time.Time     `json:"achieved_at"`
	CreatedAt   time.Time      `json:"created_at"`
}

func (q *Queries) ListGoals(ctx context.Context, userID uuid.UUID) ([]ListGoalsRow, error) {
	rows, err := q.db.Query(ctx, listGoals, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGoalsRow{}
	for rows.Next() {
		var i ListGoalsRow
		if err := rows.Scan(
			&i.ID,
			&i.GoalType,
			&i.TargetValue,
			&i.StartValue,
			&i.TargetDate,
			&i.Status,
			&i.AchievedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMeasurements = `-- name: ListMeasurements :many
SELECT id, measured_at::text AS measured_at, weight_kg, body_fat_pct FROM public.body_measurements
WHERE user_id = $1
ORDER BY measured_at DESC, created_at DESC
LIMIT $2::int
`

type ListMeasurementsParams struct {
	UserID  uuid.UUID `json:"user_id"`
	MaxRows int32     `json:"max_rows"`
}

type ListMeasurementsRow struct {
	ID         uuid.UUID      `json:"id"`
	MeasuredAt string         `json:"measured_at"`
	WeightKg   pgtype.Numeric `json:"weight_kg"`
	BodyFatPct pgtype.Numeric `json:"body_fat_pct"`
}

func (q *Queries) ListMeasurements(ctx context.Context, arg ListMeasurementsParams) ([]ListMeasurementsRow, error) {
	rows, err := q.db.Query(ctx, listMeasurements, arg.UserID, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMeasurementsRow{}
	for rows.Next() {
		var i ListMeasurementsRow
		if err := rows.Scan(
			&i.ID,
			&i.MeasuredAt,
			&i.WeightKg,
			&i.BodyFatPct,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionLogsSince = `-- name: ListSessionLogsSince :many
SELECT created_at, sport, actual FROM public.session_logs
WHERE user_id = $1 AND created_at >= $2::timestamptz
ORDER BY created_at
`

type ListSessionLogsSinceParams struct {
	UserID uuid.UUID `json:"user_id"`
	Since  time.Time `json:"since"`
}

type ListSessionLogsSinceRow struct {
	CreatedAt time.Time `json:"created_at"`
	Sport     string    `json:"sport"`
	Actual    []byte    `json:"actual"`
}

func (q *Queries) ListSessionLogsSince(ctx context.Context, arg ListSessionLogsSinceParams) ([]ListSessionLogsSinceRow, error) {
	rows, err := q.db.Query(ctx, listSessionLogsSince, arg.UserID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSessionLogsSinceRow{}
	for rows.Next() {
		var i ListSessionLogsSinceRow
		if err := rows.Scan(&i.CreatedAt, &i.Sport, &i.Actual); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockActiveMeasurementGoals = `-- name: LockActiveMeasurementGoals :many
SELECT id, goal_type, target_value, start_value FROM public.goals
WHERE user_id = $1 AND status = 'active' AND goal_type IN ('weight', 'body_fat_pct')
ORDER BY created_at
FOR UPDATE
`

type LockActiveMeasurementGoalsRow struct {
	ID          uuid.UUID      `json:"id"`
	GoalType    string         `json:"goal_type"`
	TargetValue pgtype.Numeric `json:"target_value"`
	StartValue  pgtype.Numeric `json:"start_value"`
}

func (q *Queries) LockActiveMeasurementGoals(ctx context.Context, userID uuid.UUID) ([]LockActiveMeasurementGoalsRow, error) {
	rows, err := q.db.Query(ctx, lockActiveMeasurementGoals, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LockActiveMeasurementGoalsRow{}
	for rows.Next() {
		var i LockActiveMeasurementGoalsRow
		if err := rows.Scan(
			&i.ID,
			&i.GoalType,
			&i.TargetValue,
			&i.StartValue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markGoalAchieved = `-- name: MarkGoalAchieved :execrows
UPDATE public.goals SET status = 'achieved', achieved_at = now()
WHERE id = $1 AND user_id = $2 AND status = 'active'
`

type MarkGoalAchievedParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

// Only an active goal settles (0 rows: already settled).
func (q *Queries) MarkGoalAchieved(ctx context.Context, arg MarkGoalAchievedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markGoalAchieved, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const profileOverview = `-- name: ProfileOverview :one
SELECT u.created_at AS joined_at, p.avatar_url,
       (SELECT count(*) FROM public.logs l WHERE l.user_id = p.id AND l.status = 'completed')::int AS workout_count
FROM public.profiles p JOIN public.users u ON u.id = p.id
WHERE p.id = $1
`

type ProfileOverviewRow struct {
	JoinedAt     time.Time `json:"joined_at"`
	AvatarUrl    *string   `json:"avatar_url"`
	WorkoutCount int32     `json:"workout_count"`
}

func (q *Queries) ProfileOverview(ctx context.Context, userID uuid.UUID) (ProfileOverviewRow, error) {
	row := q.db.QueryRow(ctx, profileOverview, userID)
	var i ProfileOverviewRow
	err := row.Scan(&i.JoinedAt, &i.AvatarUrl, &i.WorkoutCount)
	return i, err
}

const recentXP = `-- name: RecentXP :many
SELECT id, amount, reason, created_at FROM public.xp_transactions
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2::int
`

type RecentXPParams struct {
	UserID  *uuid.UUID `json:"user_id"`
	MaxRows int32      `json:"max_rows"`
}

type RecentXPRow struct {
	ID        uuid.UUID  `json:"id"`
	Amount    int32      `json:"amount"`
	Reason    *string    `json:"reason"`
	CreatedAt *time.Time `json:"created_at"`
}

func (q *Queries) RecentXP(ctx context.Context, arg RecentXPParams) ([]RecentXPRow, error) {
	rows, err := q.db.Query(ctx, recentXP, arg.UserID, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecentXPRow{}
	for rows.Next() {
		var i RecentXPRow
		if err := rows.Scan(
			&i.ID,
			&i.Amount,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const refreshMeasurementSnapshot = `-- name: RefreshMeasurementSnapshot :exec
UPDATE public.profiles
SET weight_kg = COALESCE($1::float8, weight_kg),
    body_fat_pct = COALESCE($2::float8, body_fat_pct)
WHERE id = $3
`

type RefreshMeasurementSnapshotParams struct {
	WeightKg   pgtype.Float8 `json:"weight_kg"`
	BodyFatPct pgtype.Float8 `json:"body_fat_pct"`
	UserID     uuid.UUID     `json:"user_id"`
}

func (q *Queries) RefreshMeasurementSnapshot(ctx context.Context, arg RefreshMeasurementSnapshotParams) error {
	_, err := q.db.Exec(ctx, refreshMeasurementSnapshot, arg.WeightKg, arg.BodyFatPct, arg.UserID)
	return err
}

const setGoalStart = `-- name: SetGoalStart :exec
UPDATE public.goals SET start_value = $1::float8
WHERE id = $2 AND user_id = $3
`

type SetGoalStartParams struct {
	StartValue float64   `json:"start_value"`
	ID         uuid.UUID `json:"id"`
	UserID     uuid.UUID `json:"user_id"`
}

func (q *Queries) SetGoalStart(ctx context.Context, arg SetGoalStartParams) error {
	_, err := q.db.Exec(ctx, setGoalStart, arg.StartValue, arg.ID, arg.UserID)
	return err
}

const setNutritionSharing = `-- name: SetNutritionSharing :exec
UPDATE public.profiles SET nutrition_sharing_enabled = $1 WHERE id = $2
`

type SetNutritionSharingParams struct {
	Enabled bool      `json:"enabled"`
	UserID  uuid.UUID `json:"user_id"`
}

func (q *Queries) SetNutritionSharing(ctx context.Context, arg SetNutritionSharingParams) error {
	_, err := q.db.Exec(ctx, setNutritionSharing, arg.Enabled, arg.UserID)
	return err
}

const updateBodyProfile = `-- name: UpdateBodyProfile :exec
UPDATE public.profiles
SET birth_date = CAST($1::text AS date), sex = $2::text,
    height_cm = $3::float8, training_history = $4::text,
    country = $5::text
WHERE id = $6
`

type UpdateBodyProfileParams struct {
	BirthDate       *string       `json:"birth_date"`
	Sex             *string       `json:"sex"`
	HeightCm        pgtype.Float8 `json:"height_cm"`
	TrainingHistory *string       `json:"training_history"`
	Country         *string       `json:"country"`
	UserID          uuid.UUID     `json:"user_id"`
}

func (q *Queries) UpdateBodyProfile(ctx context.Context, arg UpdateBodyProfileParams) error {
	_, err := q.db.Exec(ctx, updateBodyProfile,
		arg.BirthDate,
		arg.Sex,
		arg.HeightCm,
		arg.TrainingHistory,
		arg.Country,
		arg.UserID,
	)
	return err
}
