// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: routine.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteQuota = `-- name: DeleteQuota :execrows
DELETE FROM public.weekly_quotas WHERE sport_type_id = $1 AND user_id = $2
`

type DeleteQuotaParams struct {
	SportTypeID int64     `json:"sport_type_id"`
	UserID      uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteQuota(ctx context.Context, arg DeleteQuotaParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteQuota, arg.SportTypeID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSchedule = `-- name: DeleteSchedule :execrows
DELETE FROM public.schedules WHERE id = $1 AND user_id = $2::uuid
`

type DeleteScheduleParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteSchedule(ctx context.Context, arg DeleteScheduleParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSchedule, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertSchedule = `-- name: InsertSchedule :exec
INSERT INTO public.schedules (user_id, sport_type_id, day_of_week, "time", ends_on)
VALUES ($1::uuid, $2::bigint, $3,
        CAST($4::text AS time), CAST($5::text AS date))
`

type InsertScheduleParams struct {
	UserID      uuid.UUID `json:"user_id"`
	SportTypeID int64     `json:"sport_type_id"`
	DayOfWeek   int16     `json:"day_of_week"`
	Time        *string   `json:"time"`
	EndsOn      *string   `json:"ends_on"`
}

func (q *Queries) InsertSchedule(ctx context.Context, arg InsertScheduleParams) error {
	_, err := q.db.Exec(ctx, insertSchedule,
		arg.UserID,
		arg.SportTypeID,
		arg.DayOfWeek,
		arg.Time,
		arg.EndsOn,
	)
	return err
}

const latestActivePlan = `-- name: LatestActivePlan :one
SELECT id, created_at, weeks_total
FROM public.training_plans
WHERE user_id = $1 AND status = 'active'
ORDER BY created_at DESC
LIMIT 1
`

type LatestActivePlanRow struct {
	ID         uuid.UUID `json:"id"`
	CreatedAt  time.Time `json:"created_at"`
	WeeksTotal int32     `json:"weeks_total"`
}

// A user may hold several active plans (one per discipline); the week view
// shows the newest, as the legacy page did.
func (q *Queries) LatestActivePlan(ctx context.Context, userID uuid.UUID) (LatestActivePlanRow, error) {
	row := q.db.QueryRow(ctx, latestActivePlan, userID)
	var i LatestActivePlanRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.WeeksTotal)
	return i, err
}

const listLogsBetween = `-- name: ListLogsBetween :many
SELECT sport_type_id, date::text AS date, status::text AS status
FROM public.logs
WHERE user_id = $1::uuid
  AND date BETWEEN CAST($2::text AS date) AND CAST($3::text AS date)
`

type ListLogsBetweenParams struct {
	UserID   uuid.UUID `json:"user_id"`
	FromDate string    `json:"from_date"`
	ToDate   string    `json:"to_date"`
}

type ListLogsBetweenRow struct {
	SportTypeID *int64 `json:"sport_type_id"`
	Date        string `json:"date"`
	Status      string `json:"status"`
}

func (q *Queries) ListLogsBetween(ctx context.Context, arg ListLogsBetweenParams) ([]ListLogsBetweenRow, error) {
	rows, err := q.db.Query(ctx, listLogsBetween, arg.UserID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLogsBetweenRow{}
	for rows.Next() {
		var i ListLogsBetweenRow
		if err := rows.Scan(&i.SportTypeID, &i.Date, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlanWeekItems = `-- name: ListPlanWeekItems :many
SELECT i.id, i.day_of_week, i.item_type, i.title, i.description, i.details, i.is_completed
FROM public.plan_items i
JOIN public.training_plans p ON p.id = i.plan_id
WHERE i.plan_id = $1 AND p.user_id = $2 AND i.week = $3
ORDER BY i.day_of_week, i.id
`

type ListPlanWeekItemsParams struct {
	PlanID uuid.UUID `json:"plan_id"`
	UserID uuid.UUID `json:"user_id"`
	Week   int32     `json:"week"`
}

type ListPlanWeekItemsRow struct {
	ID          uuid.UUID `json:"id"`
	DayOfWeek   int16     `json:"day_of_week"`
	ItemType    string    `json:"item_type"`
	Title       string    `json:"title"`
	Description *string   `json:"description"`
	Details     []byte    `json:"details"`
	IsCompleted bool      `json:"is_completed"`
}

func (q *Queries) ListPlanWeekItems(ctx context.Context, arg ListPlanWeekItemsParams) ([]ListPlanWeekItemsRow, error) {
	rows, err := q.db.Query(ctx, listPlanWeekItems, arg.PlanID, arg.UserID, arg.Week)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlanWeekItemsRow{}
	for rows.Next() {
		var i ListPlanWeekItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.DayOfWeek,
			&i.ItemType,
			&i.Title,
			&i.Description,
			&i.Details,
			&i.IsCompleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuotas = `-- name: ListQuotas :many
SELECT q.id, q.sport_type_id, st.name AS sport_name, q.sessions_per_week
FROM public.weekly_quotas q
LEFT JOIN public.sport_types st ON st.id = q.sport_type_id
WHERE q.user_id = $1
ORDER BY q.created_at, q.id
`

type ListQuotasRow struct {
	ID              uuid.UUID `json:"id"`
	SportTypeID     int64     `json:"sport_type_id"`
	SportName       *string   `json:"sport_name"`
	SessionsPerWeek int32     `json:"sessions_per_week"`
}

func (q *Queries) ListQuotas(ctx context.Context, userID uuid.UUID) ([]ListQuotasRow, error) {
	rows, err := q.db.Query(ctx, listQuotas, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListQuotasRow{}
	for rows.Next() {
		var i ListQuotasRow
		if err := rows.Scan(
			&i.ID,
			&i.SportTypeID,
			&i.SportName,
			&i.SessionsPerWeek,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchedules = `-- name: ListSchedules :many
SELECT s.id, s.sport_type_id, st.name AS sport_name, s.day_of_week, s."time", s.ends_on,
       st.xp_multiplier
FROM public.schedules s
LEFT JOIN public.sport_types st ON st.id = s.sport_type_id
WHERE s.user_id = $1::uuid
ORDER BY s.day_of_week, s."time" NULLS LAST, s.created_at, s.id
`

type ListSchedulesRow struct {
	ID           uuid.UUID   `json:"id"`
	SportTypeID  *int64      `json:"sport_type_id"`
	SportName    *string     `json:"sport_name"`
	DayOfWeek    int16       `json:"day_of_week"`
	Time         pgtype.Time `json:"time"`
	EndsOn       pgtype.Date `json:"ends_on"`
	XpMultiplier *float32    `json:"xp_multiplier"`
}

func (q *Queries) ListSchedules(ctx context.Context, userID uuid.UUID) ([]ListSchedulesRow, error) {
	rows, err := q.db.Query(ctx, listSchedules, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSchedulesRow{}
	for rows.Next() {
		var i ListSchedulesRow
		if err := rows.Scan(
			&i.ID,
			&i.SportTypeID,
			&i.SportName,
			&i.DayOfWeek,
			&i.Time,
			&i.EndsOn,
			&i.XpMultiplier,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSportTypes = `-- name: ListSportTypes :many

SELECT id, name, xp_multiplier
FROM public.sport_types
WHERE name IS NOT NULL
ORDER BY id
`

type ListSportTypesRow struct {
	ID           int64    `json:"id"`
	Name         *string  `json:"name"`
	XpMultiplier *float32 `json:"xp_multiplier"`
}

// "My week": sport types, fixed sessions (schedules), weekly targets (quotas),
// and the active plan's items. Run with the coachin_app pool inside
// store.WithUser; every user-owned query also filters by user_id explicitly.
func (q *Queries) ListSportTypes(ctx context.Context) ([]ListSportTypesRow, error) {
	rows, err := q.db.Query(ctx, listSportTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSportTypesRow{}
	for rows.Next() {
		var i ListSportTypesRow
		if err := rows.Scan(&i.ID, &i.Name, &i.XpMultiplier); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sportTypeExists = `-- name: SportTypeExists :one
SELECT EXISTS (SELECT 1 FROM public.sport_types WHERE id = $1)
`

func (q *Queries) SportTypeExists(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRow(ctx, sportTypeExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const upsertQuota = `-- name: UpsertQuota :exec
INSERT INTO public.weekly_quotas (user_id, sport_type_id, sessions_per_week)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, sport_type_id) DO UPDATE SET sessions_per_week = EXCLUDED.sessions_per_week
`

type UpsertQuotaParams struct {
	UserID          uuid.UUID `json:"user_id"`
	SportTypeID     int64     `json:"sport_type_id"`
	SessionsPerWeek int32     `json:"sessions_per_week"`
}

func (q *Queries) UpsertQuota(ctx context.Context, arg UpsertQuotaParams) error {
	_, err := q.db.Exec(ctx, upsertQuota, arg.UserID, arg.SportTypeID, arg.SessionsPerWeek)
	return err
}
