// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: supplements.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const countSupplements = `-- name: CountSupplements :one
SELECT count(*)::int FROM public.supplements WHERE user_id = $1
`

func (q *Queries) CountSupplements(ctx context.Context, userID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countSupplements, userID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteSupplement = `-- name: DeleteSupplement :exec
DELETE FROM public.supplements WHERE id = $1 AND user_id = $2
`

type DeleteSupplementParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteSupplement(ctx context.Context, arg DeleteSupplementParams) error {
	_, err := q.db.Exec(ctx, deleteSupplement, arg.ID, arg.UserID)
	return err
}

const hasAnySchedule = `-- name: HasAnySchedule :one
SELECT EXISTS (SELECT 1 FROM public.schedules WHERE user_id = $1::uuid)
`

func (q *Queries) HasAnySchedule(ctx context.Context, userID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasAnySchedule, userID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertSupplement = `-- name: InsertSupplement :exec
INSERT INTO public.supplements (user_id, name, dose, schedule_type, days_of_week)
VALUES ($1, $2, $3, $4, $5::smallint[])
`

type InsertSupplementParams struct {
	UserID       uuid.UUID `json:"user_id"`
	Name         string    `json:"name"`
	Dose         *string   `json:"dose"`
	ScheduleType string    `json:"schedule_type"`
	DaysOfWeek   []int16   `json:"days_of_week"`
}

func (q *Queries) InsertSupplement(ctx context.Context, arg InsertSupplementParams) error {
	_, err := q.db.Exec(ctx, insertSupplement,
		arg.UserID,
		arg.Name,
		arg.Dose,
		arg.ScheduleType,
		arg.DaysOfWeek,
	)
	return err
}

const listSupplements = `-- name: ListSupplements :many

SELECT id, name, dose, schedule_type, days_of_week::int[] AS days_of_week
FROM public.supplements
WHERE user_id = $1
ORDER BY created_at, id
`

type ListSupplementsRow struct {
	ID           uuid.UUID `json:"id"`
	Name         string    `json:"name"`
	Dose         *string   `json:"dose"`
	ScheduleType string    `json:"schedule_type"`
	DaysOfWeek   []int32   `json:"days_of_week"`
}

// Daily stack: supplements and their taken-today logs. FORMULAS.md §13 —
// informational only (never XP, streaks, or hearts).
func (q *Queries) ListSupplements(ctx context.Context, userID uuid.UUID) ([]ListSupplementsRow, error) {
	rows, err := q.db.Query(ctx, listSupplements, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSupplementsRow{}
	for rows.Next() {
		var i ListSupplementsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Dose,
			&i.ScheduleType,
			&i.DaysOfWeek,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTakenSupplementsOn = `-- name: ListTakenSupplementsOn :many
SELECT supplement_id
FROM public.supplement_logs
WHERE user_id = $1 AND date = CAST($2::text AS date)
`

type ListTakenSupplementsOnParams struct {
	UserID uuid.UUID `json:"user_id"`
	OnDate string    `json:"on_date"`
}

func (q *Queries) ListTakenSupplementsOn(ctx context.Context, arg ListTakenSupplementsOnParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listTakenSupplementsOn, arg.UserID, arg.OnDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var supplement_id uuid.UUID
		if err := rows.Scan(&supplement_id); err != nil {
			return nil, err
		}
		items = append(items, supplement_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const logSupplementTaken = `-- name: LogSupplementTaken :exec
INSERT INTO public.supplement_logs (user_id, supplement_id, date)
VALUES ($1, $2, CAST($3::text AS date))
ON CONFLICT (supplement_id, date) DO NOTHING
`

type LogSupplementTakenParams struct {
	UserID       uuid.UUID `json:"user_id"`
	SupplementID uuid.UUID `json:"supplement_id"`
	OnDate       string    `json:"on_date"`
}

// A double tap is fine: one row per supplement per day.
func (q *Queries) LogSupplementTaken(ctx context.Context, arg LogSupplementTakenParams) error {
	_, err := q.db.Exec(ctx, logSupplementTaken, arg.UserID, arg.SupplementID, arg.OnDate)
	return err
}

const supplementOwned = `-- name: SupplementOwned :one
SELECT EXISTS (SELECT 1 FROM public.supplements WHERE id = $1 AND user_id = $2)
`

type SupplementOwnedParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) SupplementOwned(ctx context.Context, arg SupplementOwnedParams) (bool, error) {
	row := q.db.QueryRow(ctx, supplementOwned, arg.ID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const unlogSupplementTaken = `-- name: UnlogSupplementTaken :exec
DELETE FROM public.supplement_logs
WHERE supplement_id = $1 AND user_id = $2
  AND date = CAST($3::text AS date)
`

type UnlogSupplementTakenParams struct {
	SupplementID uuid.UUID `json:"supplement_id"`
	UserID       uuid.UUID `json:"user_id"`
	OnDate       string    `json:"on_date"`
}

func (q *Queries) UnlogSupplementTaken(ctx context.Context, arg UnlogSupplementTakenParams) error {
	_, err := q.db.Exec(ctx, unlogSupplementTaken, arg.SupplementID, arg.UserID, arg.OnDate)
	return err
}

const updateSupplementSchedule = `-- name: UpdateSupplementSchedule :execrows
UPDATE public.supplements
SET schedule_type = $1, days_of_week = $2::smallint[]
WHERE id = $3 AND user_id = $4
`

type UpdateSupplementScheduleParams struct {
	ScheduleType string    `json:"schedule_type"`
	DaysOfWeek   []int16   `json:"days_of_week"`
	ID           uuid.UUID `json:"id"`
	UserID       uuid.UUID `json:"user_id"`
}

func (q *Queries) UpdateSupplementSchedule(ctx context.Context, arg UpdateSupplementScheduleParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateSupplementSchedule,
		arg.ScheduleType,
		arg.DaysOfWeek,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
