// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: today.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const activePlanSlots = `-- name: ActivePlanSlots :many
SELECT tp.id, tp.created_at, tp.weeks_total, pi.week, pi.day_of_week::int AS day_of_week
FROM public.training_plans tp
JOIN public.plan_items pi ON pi.plan_id = tp.id
WHERE tp.user_id = $1 AND tp.status = 'active' AND pi.item_type <> 'meal_note'
`

type ActivePlanSlotsRow struct {
	ID         uuid.UUID `json:"id"`
	CreatedAt  time.Time `json:"created_at"`
	WeeksTotal int32     `json:"weeks_total"`
	Week       int32     `json:"week"`
	DayOfWeek  int32     `json:"day_of_week"`
}

// Every active plan's non-meal (week, weekday) slots, with the plan's start and length.
func (q *Queries) ActivePlanSlots(ctx context.Context, userID uuid.UUID) ([]ActivePlanSlotsRow, error) {
	rows, err := q.db.Query(ctx, activePlanSlots, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActivePlanSlotsRow{}
	for rows.Next() {
		var i ActivePlanSlotsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.WeeksTotal,
			&i.Week,
			&i.DayOfWeek,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const addProfileXP = `-- name: AddProfileXP :one
UPDATE public.profiles
SET xp = GREATEST(COALESCE(xp, 0) + $1::int, 0),
    level = FLOOR(GREATEST(COALESCE(xp, 0) + $1::int, 0) / 1000.0) + 1
WHERE id = $2
RETURNING COALESCE(xp, 0)::bigint AS xp
`

type AddProfileXPParams struct {
	Amount int32     `json:"amount"`
	UserID uuid.UUID `json:"user_id"`
}

// The league tier follows via the sync_league_tier trigger.
func (q *Queries) AddProfileXP(ctx context.Context, arg AddProfileXPParams) (int64, error) {
	row := q.db.QueryRow(ctx, addProfileXP, arg.Amount, arg.UserID)
	var xp int64
	err := row.Scan(&xp)
	return xp, err
}

const hasLoggedSportOn = `-- name: HasLoggedSportOn :one
SELECT EXISTS (
  SELECT 1 FROM public.logs
  WHERE user_id = $1::uuid AND sport_type_id = $2::bigint
    AND date = CAST($3::text AS date)
)
`

type HasLoggedSportOnParams struct {
	UserID      uuid.UUID `json:"user_id"`
	SportTypeID int64     `json:"sport_type_id"`
	OnDate      string    `json:"on_date"`
}

func (q *Queries) HasLoggedSportOn(ctx context.Context, arg HasLoggedSportOnParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasLoggedSportOn, arg.UserID, arg.SportTypeID, arg.OnDate)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertImportedLog = `-- name: InsertImportedLog :exec
INSERT INTO public.logs (user_id, sport_type_id, date, status, notes)
VALUES ($1::uuid, $2::bigint, CAST($3::text AS date), 'completed', $4::text)
`

type InsertImportedLogParams struct {
	UserID      uuid.UUID `json:"user_id"`
	SportTypeID int64     `json:"sport_type_id"`
	OnDate      string    `json:"on_date"`
	Notes       string    `json:"notes"`
}

func (q *Queries) InsertImportedLog(ctx context.Context, arg InsertImportedLogParams) error {
	_, err := q.db.Exec(ctx, insertImportedLog,
		arg.UserID,
		arg.SportTypeID,
		arg.OnDate,
		arg.Notes,
	)
	return err
}

const insertWorkoutLog = `-- name: InsertWorkoutLog :exec
INSERT INTO public.logs (user_id, sport_type_id, date, status)
VALUES ($1::uuid, $2::bigint, CAST($3::text AS date), 'completed')
`

type InsertWorkoutLogParams struct {
	UserID      uuid.UUID `json:"user_id"`
	SportTypeID int64     `json:"sport_type_id"`
	OnDate      string    `json:"on_date"`
}

func (q *Queries) InsertWorkoutLog(ctx context.Context, arg InsertWorkoutLogParams) error {
	_, err := q.db.Exec(ctx, insertWorkoutLog, arg.UserID, arg.SportTypeID, arg.OnDate)
	return err
}

const insertXPTransaction = `-- name: InsertXPTransaction :exec
INSERT INTO public.xp_transactions (user_id, amount, reason)
VALUES ($1::uuid, $2, $3::text)
`

type InsertXPTransactionParams struct {
	UserID uuid.UUID `json:"user_id"`
	Amount int32     `json:"amount"`
	Reason string    `json:"reason"`
}

func (q *Queries) InsertXPTransaction(ctx context.Context, arg InsertXPTransactionParams) error {
	_, err := q.db.Exec(ctx, insertXPTransaction, arg.UserID, arg.Amount, arg.Reason)
	return err
}

const lastProgressPhotoAt = `-- name: LastProgressPhotoAt :one
SELECT created_at
FROM public.body_photos
WHERE user_id = $1 AND kind = 'progress'
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) LastProgressPhotoAt(ctx context.Context, userID uuid.UUID) (time.Time, error) {
	row := q.db.QueryRow(ctx, lastProgressPhotoAt, userID)
	var created_at time.Time
	err := row.Scan(&created_at)
	return created_at, err
}

const listActivePlans = `-- name: ListActivePlans :many
SELECT id, created_at, weeks_total
FROM public.training_plans
WHERE user_id = $1 AND status = 'active'
ORDER BY plan_kind, created_at
`

type ListActivePlansRow struct {
	ID         uuid.UUID `json:"id"`
	CreatedAt  time.Time `json:"created_at"`
	WeeksTotal int32     `json:"weeks_total"`
}

func (q *Queries) ListActivePlans(ctx context.Context, userID uuid.UUID) ([]ListActivePlansRow, error) {
	rows, err := q.db.Query(ctx, listActivePlans, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActivePlansRow{}
	for rows.Next() {
		var i ListActivePlansRow
		if err := rows.Scan(&i.ID, &i.CreatedAt, &i.WeeksTotal); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLoggedSportsOn = `-- name: ListLoggedSportsOn :many
SELECT DISTINCT sport_type_id
FROM public.logs
WHERE user_id = $1::uuid AND date = CAST($2::text AS date)
  AND sport_type_id IS NOT NULL
`

type ListLoggedSportsOnParams struct {
	UserID uuid.UUID `json:"user_id"`
	OnDate string    `json:"on_date"`
}

func (q *Queries) ListLoggedSportsOn(ctx context.Context, arg ListLoggedSportsOnParams) ([]*int64, error) {
	rows, err := q.db.Query(ctx, listLoggedSportsOn, arg.UserID, arg.OnDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*int64{}
	for rows.Next() {
		var sport_type_id *int64
		if err := rows.Scan(&sport_type_id); err != nil {
			return nil, err
		}
		items = append(items, sport_type_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlanItemsForWeeks = `-- name: ListPlanItemsForWeeks :many
SELECT i.id, i.plan_id, i.week, i.day_of_week, i.item_type, i.title, i.description, i.details, i.is_completed
FROM public.plan_items i
JOIN public.training_plans p ON p.id = i.plan_id
WHERE p.user_id = $1 AND i.day_of_week = $2
  -- Parallel arrays: the i-th plan is in its week i (unnests zip in step).
  AND (i.plan_id, i.week) IN (SELECT unnest($3::uuid[]), unnest($4::int[]))
ORDER BY p.plan_kind, p.created_at, i.id
`

type ListPlanItemsForWeeksParams struct {
	UserID    uuid.UUID   `json:"user_id"`
	DayOfWeek int16       `json:"day_of_week"`
	PlanIds   []uuid.UUID `json:"plan_ids"`
	Weeks     []int32     `json:"weeks"`
}

type ListPlanItemsForWeeksRow struct {
	ID          uuid.UUID `json:"id"`
	PlanID      uuid.UUID `json:"plan_id"`
	Week        int32     `json:"week"`
	DayOfWeek   int16     `json:"day_of_week"`
	ItemType    string    `json:"item_type"`
	Title       string    `json:"title"`
	Description *string   `json:"description"`
	Details     []byte    `json:"details"`
	IsCompleted bool      `json:"is_completed"`
}

// Items on one weekday for each (plan, week) pair.
func (q *Queries) ListPlanItemsForWeeks(ctx context.Context, arg ListPlanItemsForWeeksParams) ([]ListPlanItemsForWeeksRow, error) {
	rows, err := q.db.Query(ctx, listPlanItemsForWeeks,
		arg.UserID,
		arg.DayOfWeek,
		arg.PlanIds,
		arg.Weeks,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlanItemsForWeeksRow{}
	for rows.Next() {
		var i ListPlanItemsForWeeksRow
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.Week,
			&i.DayOfWeek,
			&i.ItemType,
			&i.Title,
			&i.Description,
			&i.Details,
			&i.IsCompleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsOn = `-- name: ListSessionsOn :many
SELECT s.id, s.sport_type_id, st.name AS sport_name, s."time", st.xp_multiplier
FROM public.schedules s
LEFT JOIN public.sport_types st ON st.id = s.sport_type_id
WHERE s.user_id = $1::uuid
  AND s.day_of_week = $2
  AND (s.starts_on IS NULL OR s.starts_on <= CAST($3::text AS date))
  AND (s.ends_on IS NULL OR s.ends_on >= CAST($3::text AS date))
ORDER BY s."time" NULLS LAST, s.created_at, s.id
`

type ListSessionsOnParams struct {
	UserID    uuid.UUID `json:"user_id"`
	DayOfWeek int16     `json:"day_of_week"`
	OnDate    string    `json:"on_date"`
}

type ListSessionsOnRow struct {
	ID           uuid.UUID   `json:"id"`
	SportTypeID  *int64      `json:"sport_type_id"`
	SportName    *string     `json:"sport_name"`
	Time         pgtype.Time `json:"time"`
	XpMultiplier *float32    `json:"xp_multiplier"`
}

// Fixed sessions on a weekday, inside their starts_on/ends_on window.
func (q *Queries) ListSessionsOn(ctx context.Context, arg ListSessionsOnParams) ([]ListSessionsOnRow, error) {
	rows, err := q.db.Query(ctx, listSessionsOn, arg.UserID, arg.DayOfWeek, arg.OnDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSessionsOnRow{}
	for rows.Next() {
		var i ListSessionsOnRow
		if err := rows.Scan(
			&i.ID,
			&i.SportTypeID,
			&i.SportName,
			&i.Time,
			&i.XpMultiplier,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockProfile = `-- name: LockProfile :exec
SELECT 1 FROM public.profiles WHERE id = $1 FOR UPDATE
`

// Serializes a user's XP awards (duplicate checks + balance update).
func (q *Queries) LockProfile(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, lockProfile, userID)
	return err
}

const loggedDatesOf = `-- name: LoggedDatesOf :many
SELECT DISTINCT date::text AS on_date FROM public.logs
WHERE user_id = $1 AND sport_type_id = $2 AND status = 'completed'
  AND date = ANY(CAST($3::text[] AS date[]))
`

type LoggedDatesOfParams struct {
	UserID      *uuid.UUID `json:"user_id"`
	SportTypeID *int64     `json:"sport_type_id"`
	Dates       []string   `json:"dates"`
}

// Which of the dates already have a completed log of the sport.
func (q *Queries) LoggedDatesOf(ctx context.Context, arg LoggedDatesOfParams) ([]string, error) {
	rows, err := q.db.Query(ctx, loggedDatesOf, arg.UserID, arg.SportTypeID, arg.Dates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var on_date string
		if err := rows.Scan(&on_date); err != nil {
			return nil, err
		}
		items = append(items, on_date)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const runningSport = `-- name: RunningSport :one
SELECT id, xp_multiplier FROM public.sport_types WHERE name ILIKE '%run%' ORDER BY id LIMIT 1
`

type RunningSportRow struct {
	ID           int64    `json:"id"`
	XpMultiplier *float32 `json:"xp_multiplier"`
}

// The sport watch-file imports log under (legacy: first sport named like "run").
func (q *Queries) RunningSport(ctx context.Context) (RunningSportRow, error) {
	row := q.db.QueryRow(ctx, runningSport)
	var i RunningSportRow
	err := row.Scan(&i.ID, &i.XpMultiplier)
	return i, err
}

const saveStreak = `-- name: SaveStreak :exec
UPDATE public.profiles
SET current_streak = $1::int, best_streak = $2::int, hearts = $3::int,
    streak_evaluated_date = CAST($4::text AS date)
WHERE id = $5
`

type SaveStreakParams struct {
	Streak         int32     `json:"streak"`
	Best           int32     `json:"best"`
	Hearts         int32     `json:"hearts"`
	SettledThrough string    `json:"settled_through"`
	UserID         uuid.UUID `json:"user_id"`
}

func (q *Queries) SaveStreak(ctx context.Context, arg SaveStreakParams) error {
	_, err := q.db.Exec(ctx, saveStreak,
		arg.Streak,
		arg.Best,
		arg.Hearts,
		arg.SettledThrough,
		arg.UserID,
	)
	return err
}

const sportMultiplier = `-- name: SportMultiplier :one
SELECT xp_multiplier FROM public.sport_types WHERE id = $1
`

func (q *Queries) SportMultiplier(ctx context.Context, id int64) (*float32, error) {
	row := q.db.QueryRow(ctx, sportMultiplier, id)
	var xp_multiplier *float32
	err := row.Scan(&xp_multiplier)
	return xp_multiplier, err
}

const streakSchedules = `-- name: StreakSchedules :many
SELECT day_of_week::int AS day_of_week, starts_on, ends_on FROM public.schedules WHERE user_id = $1
`

type StreakSchedulesRow struct {
	DayOfWeek int32       `json:"day_of_week"`
	StartsOn  pgtype.Date `json:"starts_on"`
	EndsOn    pgtype.Date `json:"ends_on"`
}

func (q *Queries) StreakSchedules(ctx context.Context, userID *uuid.UUID) ([]StreakSchedulesRow, error) {
	rows, err := q.db.Query(ctx, streakSchedules, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StreakSchedulesRow{}
	for rows.Next() {
		var i StreakSchedulesRow
		if err := rows.Scan(&i.DayOfWeek, &i.StartsOn, &i.EndsOn); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const streakState = `-- name: StreakState :one

SELECT COALESCE(current_streak, 0)::int AS streak, COALESCE(best_streak, 0)::int AS best,
       COALESCE(hearts, 3)::int AS hearts, streak_evaluated_date AS settled_through
FROM public.profiles WHERE id = $1
`

type StreakStateRow struct {
	Streak         int32       `json:"streak"`
	Best           int32       `json:"best"`
	Hearts         int32       `json:"hearts"`
	SettledThrough pgtype.Date `json:"settled_through"`
}

// Today: stats, today's sessions and plan items, workout logging.
// Run with the coachin_app pool inside store.WithUser.
// Read after LockProfile, so concurrent settles run one at a time.
func (q *Queries) StreakState(ctx context.Context, userID uuid.UUID) (StreakStateRow, error) {
	row := q.db.QueryRow(ctx, streakState, userID)
	var i StreakStateRow
	err := row.Scan(
		&i.Streak,
		&i.Best,
		&i.Hearts,
		&i.SettledThrough,
	)
	return i, err
}

const todayProfile = `-- name: TodayProfile :one
SELECT COALESCE(xp, 0)::bigint AS xp, COALESCE(current_streak, 0)::int AS current_streak,
       COALESCE(best_streak, 0)::int AS best_streak, COALESCE(hearts, 3)::int AS hearts,
       COALESCE(league_tier, 'bronze')::text AS league_tier
FROM public.profiles
WHERE id = $1
`

type TodayProfileRow struct {
	Xp            int64  `json:"xp"`
	CurrentStreak int32  `json:"current_streak"`
	BestStreak    int32  `json:"best_streak"`
	Hearts        int32  `json:"hearts"`
	LeagueTier    string `json:"league_tier"`
}

func (q *Queries) TodayProfile(ctx context.Context, userID uuid.UUID) (TodayProfileRow, error) {
	row := q.db.QueryRow(ctx, todayProfile, userID)
	var i TodayProfileRow
	err := row.Scan(
		&i.Xp,
		&i.CurrentStreak,
		&i.BestStreak,
		&i.Hearts,
		&i.LeagueTier,
	)
	return i, err
}

const trainedDates = `-- name: TrainedDates :many
SELECT DISTINCT date::text AS on_date FROM public.logs
WHERE user_id = $1 AND status = 'completed'
  AND date BETWEEN CAST($2::text AS date) AND CAST($3::text AS date)
`

type TrainedDatesParams struct {
	UserID   *uuid.UUID `json:"user_id"`
	FromDate string     `json:"from_date"`
	ToDate   string     `json:"to_date"`
}

// Dates with a completed log of any discipline.
func (q *Queries) TrainedDates(ctx context.Context, arg TrainedDatesParams) ([]string, error) {
	rows, err := q.db.Query(ctx, trainedDates, arg.UserID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var on_date string
		if err := rows.Scan(&on_date); err != nil {
			return nil, err
		}
		items = append(items, on_date)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
