// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: training.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const activeCalorieGoal = `-- name: ActiveCalorieGoal :one
SELECT target_value::float8 AS target_value FROM public.goals
WHERE user_id = $1 AND goal_type = 'calorie_intake' AND status = 'active'
LIMIT 1
`

func (q *Queries) ActiveCalorieGoal(ctx context.Context, userID uuid.UUID) (float64, error) {
	row := q.db.QueryRow(ctx, activeCalorieGoal, userID)
	var target_value float64
	err := row.Scan(&target_value)
	return target_value, err
}

const applyWeekAdjustment = `-- name: ApplyWeekAdjustment :one
SELECT public.apply_week_adjustment(
  $1::uuid, $2::int, $3::jsonb, $4::text,
  $5::text, $6::int, $7::jsonb
)::text AS result
`

type ApplyWeekAdjustmentParams struct {
	PlanID      uuid.UUID `json:"plan_id"`
	CheckinWeek int32     `json:"checkin_week"`
	Scorecard   []byte    `json:"scorecard"`
	Decision    string    `json:"decision"`
	Summary     *string   `json:"summary"`
	TargetWeek  int32     `json:"target_week"`
	Items       []byte    `json:"items"`
}

// Step A (ADR-5): records the check-in, rewrites only the target week, and
// awards +20 XP once per reviewed week.
func (q *Queries) ApplyWeekAdjustment(ctx context.Context, arg ApplyWeekAdjustmentParams) (string, error) {
	row := q.db.QueryRow(ctx, applyWeekAdjustment,
		arg.PlanID,
		arg.CheckinWeek,
		arg.Scorecard,
		arg.Decision,
		arg.Summary,
		arg.TargetWeek,
		arg.Items,
	)
	var result string
	err := row.Scan(&result)
	return result, err
}

const archivePlan = `-- name: ArchivePlan :execrows
UPDATE public.training_plans SET status = 'archived'
WHERE id = $1 AND user_id = $2 AND status = 'active'
`

type ArchivePlanParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) ArchivePlan(ctx context.Context, arg ArchivePlanParams) (int64, error) {
	result, err := q.db.Exec(ctx, archivePlan, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const athleteProfile = `-- name: AthleteProfile :one
SELECT birth_date, sex, height_cm, weight_kg, training_history, full_name, email
FROM public.profiles WHERE id = $1
`

type AthleteProfileRow struct {
	BirthDate       pgtype.Date    `json:"birth_date"`
	Sex             *string        `json:"sex"`
	HeightCm        pgtype.Numeric `json:"height_cm"`
	WeightKg        pgtype.Numeric `json:"weight_kg"`
	TrainingHistory *string        `json:"training_history"`
	FullName        *string        `json:"full_name"`
	Email           *string        `json:"email"`
}

// numeric as stored: 61.00 reads 61, as the legacy JSON API returned it.
func (q *Queries) AthleteProfile(ctx context.Context, id uuid.UUID) (AthleteProfileRow, error) {
	row := q.db.QueryRow(ctx, athleteProfile, id)
	var i AthleteProfileRow
	err := row.Scan(
		&i.BirthDate,
		&i.Sex,
		&i.HeightCm,
		&i.WeightKg,
		&i.TrainingHistory,
		&i.FullName,
		&i.Email,
	)
	return i, err
}

const coachesStudent = `-- name: CoachesStudent :one
SELECT EXISTS (
  SELECT 1 FROM public.coaching_relationships
  WHERE coach_id = $1 AND student_id = $2 AND status = 'active'
)
`

type CoachesStudentParams struct {
	CoachID   uuid.UUID `json:"coach_id"`
	StudentID uuid.UUID `json:"student_id"`
}

func (q *Queries) CoachesStudent(ctx context.Context, arg CoachesStudentParams) (bool, error) {
	row := q.db.QueryRow(ctx, coachesStudent, arg.CoachID, arg.StudentID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countLedgerReasons = `-- name: CountLedgerReasons :one
SELECT count(*) FILTER (WHERE reason = $1::text) AS awards,
       count(*) FILTER (WHERE reason = $2::text) AS undos
FROM public.xp_transactions
WHERE user_id = $3 AND reason IN ($1::text, $2::text)
`

type CountLedgerReasonsParams struct {
	AwardReason string     `json:"award_reason"`
	UndoReason  string     `json:"undo_reason"`
	UserID      *uuid.UUID `json:"user_id"`
}

type CountLedgerReasonsRow struct {
	Awards int64 `json:"awards"`
	Undos  int64 `json:"undos"`
}

// How many award and undo rows an item already has (they repeat by design).
func (q *Queries) CountLedgerReasons(ctx context.Context, arg CountLedgerReasonsParams) (CountLedgerReasonsRow, error) {
	row := q.db.QueryRow(ctx, countLedgerReasons, arg.AwardReason, arg.UndoReason, arg.UserID)
	var i CountLedgerReasonsRow
	err := row.Scan(&i.Awards, &i.Undos)
	return i, err
}

const createTrainingPlan = `-- name: CreateTrainingPlan :one
SELECT public.create_training_plan(
  CAST($1::text AS date), $2::text, $3::int,
  $4::text, $5::jsonb, $6::jsonb, $7::text,
  $8::jsonb, $9::text, $10::uuid
)::text AS result
`

type CreateTrainingPlanParams struct {
	RaceDate     *string    `json:"race_date"`
	GoalTime     *string    `json:"goal_time"`
	WeeksTotal   int32      `json:"weeks_total"`
	Summary      string     `json:"summary"`
	Intake       []byte     `json:"intake"`
	Raw          []byte     `json:"raw"`
	Model        string     `json:"model"`
	Items        []byte     `json:"items"`
	PlanKind     string     `json:"plan_kind"`
	TargetUserID *uuid.UUID `json:"target_user_id"`
}

// Step A (ADR-5): archives the same-discipline plan and saves this one,
// re-verifying the coaching relationship for coach-generated plans.
func (q *Queries) CreateTrainingPlan(ctx context.Context, arg CreateTrainingPlanParams) (string, error) {
	row := q.db.QueryRow(ctx, createTrainingPlan,
		arg.RaceDate,
		arg.GoalTime,
		arg.WeeksTotal,
		arg.Summary,
		arg.Intake,
		arg.Raw,
		arg.Model,
		arg.Items,
		arg.PlanKind,
		arg.TargetUserID,
	)
	var result string
	err := row.Scan(&result)
	return result, err
}

const deletePlanItemLog = `-- name: DeletePlanItemLog :exec
DELETE FROM public.logs WHERE user_id = $1 AND plan_item_id = $2
`

type DeletePlanItemLogParams struct {
	UserID     *uuid.UUID `json:"user_id"`
	PlanItemID *uuid.UUID `json:"plan_item_id"`
}

func (q *Queries) DeletePlanItemLog(ctx context.Context, arg DeletePlanItemLogParams) error {
	_, err := q.db.Exec(ctx, deletePlanItemLog, arg.UserID, arg.PlanItemID)
	return err
}

const getActivePlan = `-- name: GetActivePlan :one
SELECT id, weeks_total, summary, created_at, intake
FROM public.training_plans
WHERE id = $1 AND user_id = $2 AND status = 'active'
`

type GetActivePlanParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

type GetActivePlanRow struct {
	ID         uuid.UUID `json:"id"`
	WeeksTotal int32     `json:"weeks_total"`
	Summary    *string   `json:"summary"`
	CreatedAt  time.Time `json:"created_at"`
	Intake     []byte    `json:"intake"`
}

func (q *Queries) GetActivePlan(ctx context.Context, arg GetActivePlanParams) (GetActivePlanRow, error) {
	row := q.db.QueryRow(ctx, getActivePlan, arg.ID, arg.UserID)
	var i GetActivePlanRow
	err := row.Scan(
		&i.ID,
		&i.WeeksTotal,
		&i.Summary,
		&i.CreatedAt,
		&i.Intake,
	)
	return i, err
}

const getCheckin = `-- name: GetCheckin :one
SELECT c.scorecard
FROM public.weekly_checkins c
JOIN public.training_plans p ON p.id = c.plan_id
WHERE c.plan_id = $1 AND c.week = $2 AND p.user_id = $3
`

type GetCheckinParams struct {
	PlanID uuid.UUID `json:"plan_id"`
	Week   int32     `json:"week"`
	UserID uuid.UUID `json:"user_id"`
}

// A plan week's check-in, if any (the scorecard feeds the next decision).
func (q *Queries) GetCheckin(ctx context.Context, arg GetCheckinParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getCheckin, arg.PlanID, arg.Week, arg.UserID)
	var scorecard []byte
	err := row.Scan(&scorecard)
	return scorecard, err
}

const getPlanItemRef = `-- name: GetPlanItemRef :one

SELECT i.item_type, i.week, i.day_of_week, i.is_completed, p.created_at AS plan_created_at
FROM public.plan_items i
JOIN public.training_plans p ON p.id = i.plan_id
WHERE i.id = $1 AND p.user_id = $2
`

type GetPlanItemRefParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

type GetPlanItemRefRow struct {
	ItemType      string    `json:"item_type"`
	Week          int32     `json:"week"`
	DayOfWeek     int16     `json:"day_of_week"`
	IsCompleted   bool      `json:"is_completed"`
	PlanCreatedAt time.Time `json:"plan_created_at"`
}

// Training plans: plan-item completion (more arrives with the Training module).
// The item plus its plan's start, for the log-window check. Owner only.
func (q *Queries) GetPlanItemRef(ctx context.Context, arg GetPlanItemRefParams) (GetPlanItemRefRow, error) {
	row := q.db.QueryRow(ctx, getPlanItemRef, arg.ID, arg.UserID)
	var i GetPlanItemRefRow
	err := row.Scan(
		&i.ItemType,
		&i.Week,
		&i.DayOfWeek,
		&i.IsCompleted,
		&i.PlanCreatedAt,
	)
	return i, err
}

const getSessionItem = `-- name: GetSessionItem :one
SELECT i.item_type, i.title, i.details
FROM public.plan_items i
JOIN public.training_plans p ON p.id = i.plan_id
WHERE i.id = $1 AND p.user_id = $2
`

type GetSessionItemParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

type GetSessionItemRow struct {
	ItemType string `json:"item_type"`
	Title    string `json:"title"`
	Details  []byte `json:"details"`
}

func (q *Queries) GetSessionItem(ctx context.Context, arg GetSessionItemParams) (GetSessionItemRow, error) {
	row := q.db.QueryRow(ctx, getSessionItem, arg.ID, arg.UserID)
	var i GetSessionItemRow
	err := row.Scan(&i.ItemType, &i.Title, &i.Details)
	return i, err
}

const insertPlanItemLog = `-- name: InsertPlanItemLog :exec
INSERT INTO public.logs (user_id, date, sport_type_id, status, notes, plan_item_id)
VALUES ($1, CAST($2::text AS date), NULL, 'completed', $3, $4)
ON CONFLICT (plan_item_id) WHERE plan_item_id IS NOT NULL DO NOTHING
`

type InsertPlanItemLogParams struct {
	UserID     *uuid.UUID `json:"user_id"`
	OnDate     string     `json:"on_date"`
	Title      *string    `json:"title"`
	PlanItemID *uuid.UUID `json:"plan_item_id"`
}

// The completed item's log, dated the day it was marked done (one per item).
func (q *Queries) InsertPlanItemLog(ctx context.Context, arg InsertPlanItemLogParams) error {
	_, err := q.db.Exec(ctx, insertPlanItemLog,
		arg.UserID,
		arg.OnDate,
		arg.Title,
		arg.PlanItemID,
	)
	return err
}

const insertSessionLog = `-- name: InsertSessionLog :one
INSERT INTO public.session_logs (user_id, plan_item_id, sport, rpe, actual, note)
VALUES ($1, $2, $3, $4::int, $5::jsonb, $6::text)
RETURNING id
`

type InsertSessionLogParams struct {
	UserID     uuid.UUID   `json:"user_id"`
	PlanItemID uuid.UUID   `json:"plan_item_id"`
	Sport      string      `json:"sport"`
	Rpe        pgtype.Int4 `json:"rpe"`
	Actual     []byte      `json:"actual"`
	Note       *string     `json:"note"`
}

func (q *Queries) InsertSessionLog(ctx context.Context, arg InsertSessionLogParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertSessionLog,
		arg.UserID,
		arg.PlanItemID,
		arg.Sport,
		arg.Rpe,
		arg.Actual,
		arg.Note,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const latestBodyAnalysis = `-- name: LatestBodyAnalysis :one
SELECT analysis FROM public.body_photos
WHERE user_id = $1 AND kind = 'body_photo' AND analysis IS NOT NULL
ORDER BY analyzed_at DESC NULLS LAST
LIMIT 1
`

// Body photos only: a report's extracted metrics are not a body analysis
// (legacy read any kind, so a newer report hid the analysis from prompts).
func (q *Queries) LatestBodyAnalysis(ctx context.Context, userID uuid.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, latestBodyAnalysis, userID)
	var analysis []byte
	err := row.Scan(&analysis)
	return analysis, err
}

const listActivePlanItems = `-- name: ListActivePlanItems :many
SELECT i.id, i.week, i.day_of_week, i.item_type, i.title, i.description, i.details, p.created_at AS plan_created_at
FROM public.plan_items i
JOIN public.training_plans p ON p.id = i.plan_id
WHERE p.user_id = $1 AND p.status = 'active'
ORDER BY p.plan_kind, i.week, i.day_of_week, i.id
`

type ListActivePlanItemsRow struct {
	ID            uuid.UUID `json:"id"`
	Week          int32     `json:"week"`
	DayOfWeek     int16     `json:"day_of_week"`
	ItemType      string    `json:"item_type"`
	Title         string    `json:"title"`
	Description   *string   `json:"description"`
	Details       []byte    `json:"details"`
	PlanCreatedAt time.Time `json:"plan_created_at"`
}

// Every item of every active plan, for the calendar export.
func (q *Queries) ListActivePlanItems(ctx context.Context, userID uuid.UUID) ([]ListActivePlanItemsRow, error) {
	rows, err := q.db.Query(ctx, listActivePlanItems, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActivePlanItemsRow{}
	for rows.Next() {
		var i ListActivePlanItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.Week,
			&i.DayOfWeek,
			&i.ItemType,
			&i.Title,
			&i.Description,
			&i.Details,
			&i.PlanCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivePrograms = `-- name: ListActivePrograms :many
SELECT id, race_date, goal_time, weeks_total, created_at, plan_kind, intake, created_by
FROM public.training_plans
WHERE user_id = $1 AND status = 'active'
ORDER BY plan_kind, created_at
`

type ListActiveProgramsRow struct {
	ID         uuid.UUID   `json:"id"`
	RaceDate   pgtype.Date `json:"race_date"`
	GoalTime   *string     `json:"goal_time"`
	WeeksTotal int32       `json:"weeks_total"`
	CreatedAt  time.Time   `json:"created_at"`
	PlanKind   string      `json:"plan_kind"`
	Intake     []byte      `json:"intake"`
	CreatedBy  *uuid.UUID  `json:"created_by"`
}

func (q *Queries) ListActivePrograms(ctx context.Context, userID uuid.UUID) ([]ListActiveProgramsRow, error) {
	rows, err := q.db.Query(ctx, listActivePrograms, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveProgramsRow{}
	for rows.Next() {
		var i ListActiveProgramsRow
		if err := rows.Scan(
			&i.ID,
			&i.RaceDate,
			&i.GoalTime,
			&i.WeeksTotal,
			&i.CreatedAt,
			&i.PlanKind,
			&i.Intake,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnchors = `-- name: ListAnchors :many
SELECT s.day_of_week, s."time", st.name AS sport_name
FROM public.schedules s
LEFT JOIN public.sport_types st ON st.id = s.sport_type_id
WHERE s.user_id = $1::uuid
  AND (s.starts_on IS NULL OR s.starts_on <= CAST($2::text AS date))
  AND (s.ends_on IS NULL OR s.ends_on >= CAST($2::text AS date))
ORDER BY s.created_at, s.id
LIMIT 21
`

type ListAnchorsParams struct {
	UserID uuid.UUID `json:"user_id"`
	OnDate string    `json:"on_date"`
}

type ListAnchorsRow struct {
	DayOfWeek int16       `json:"day_of_week"`
	Time      pgtype.Time `json:"time"`
	SportName *string     `json:"sport_name"`
}

// The athlete's fixed sessions active on a date (max 21, as the legacy app).
func (q *Queries) ListAnchors(ctx context.Context, arg ListAnchorsParams) ([]ListAnchorsRow, error) {
	rows, err := q.db.Query(ctx, listAnchors, arg.UserID, arg.OnDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAnchorsRow{}
	for rows.Next() {
		var i ListAnchorsRow
		if err := rows.Scan(&i.DayOfWeek, &i.Time, &i.SportName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlanWeeksItems = `-- name: ListPlanWeeksItems :many
SELECT i.id, i.week, i.day_of_week, i.item_type, i.title, i.details, i.is_completed
FROM public.plan_items i
JOIN public.training_plans p ON p.id = i.plan_id
WHERE i.plan_id = $1 AND p.user_id = $2
  AND i.week BETWEEN $3::int AND $4::int
ORDER BY i.week, i.day_of_week, i.id
`

type ListPlanWeeksItemsParams struct {
	PlanID   uuid.UUID `json:"plan_id"`
	UserID   uuid.UUID `json:"user_id"`
	FromWeek int32     `json:"from_week"`
	ToWeek   int32     `json:"to_week"`
}

type ListPlanWeeksItemsRow struct {
	ID          uuid.UUID `json:"id"`
	Week        int32     `json:"week"`
	DayOfWeek   int16     `json:"day_of_week"`
	ItemType    string    `json:"item_type"`
	Title       string    `json:"title"`
	Details     []byte    `json:"details"`
	IsCompleted bool      `json:"is_completed"`
}

func (q *Queries) ListPlanWeeksItems(ctx context.Context, arg ListPlanWeeksItemsParams) ([]ListPlanWeeksItemsRow, error) {
	rows, err := q.db.Query(ctx, listPlanWeeksItems,
		arg.PlanID,
		arg.UserID,
		arg.FromWeek,
		arg.ToWeek,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlanWeeksItemsRow{}
	for rows.Next() {
		var i ListPlanWeeksItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.Week,
			&i.DayOfWeek,
			&i.ItemType,
			&i.Title,
			&i.Details,
			&i.IsCompleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewedWeeks = `-- name: ListReviewedWeeks :many
SELECT c.plan_id, c.week
FROM public.weekly_checkins c
JOIN public.training_plans p ON p.id = c.plan_id
WHERE p.user_id = $1 AND c.plan_id = ANY($2::uuid[])
`

type ListReviewedWeeksParams struct {
	UserID  uuid.UUID   `json:"user_id"`
	PlanIds []uuid.UUID `json:"plan_ids"`
}

type ListReviewedWeeksRow struct {
	PlanID uuid.UUID `json:"plan_id"`
	Week   int32     `json:"week"`
}

func (q *Queries) ListReviewedWeeks(ctx context.Context, arg ListReviewedWeeksParams) ([]ListReviewedWeeksRow, error) {
	rows, err := q.db.Query(ctx, listReviewedWeeks, arg.UserID, arg.PlanIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReviewedWeeksRow{}
	for rows.Next() {
		var i ListReviewedWeeksRow
		if err := rows.Scan(&i.PlanID, &i.Week); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionLogs = `-- name: ListSessionLogs :many
SELECT plan_item_id, actual, ai_feedback, note
FROM public.session_logs
WHERE user_id = $1 AND plan_item_id = ANY($2::uuid[])
`

type ListSessionLogsParams struct {
	UserID  uuid.UUID   `json:"user_id"`
	ItemIds []uuid.UUID `json:"item_ids"`
}

type ListSessionLogsRow struct {
	PlanItemID uuid.UUID `json:"plan_item_id"`
	Actual     []byte    `json:"actual"`
	AiFeedback []byte    `json:"ai_feedback"`
	Note       *string   `json:"note"`
}

func (q *Queries) ListSessionLogs(ctx context.Context, arg ListSessionLogsParams) ([]ListSessionLogsRow, error) {
	rows, err := q.db.Query(ctx, listSessionLogs, arg.UserID, arg.ItemIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSessionLogsRow{}
	for rows.Next() {
		var i ListSessionLogsRow
		if err := rows.Scan(
			&i.PlanItemID,
			&i.Actual,
			&i.AiFeedback,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPlanItemCompleted = `-- name: MarkPlanItemCompleted :exec
UPDATE public.plan_items i SET is_completed = true
FROM public.training_plans p
WHERE i.id = $1 AND p.id = i.plan_id AND p.user_id = $2
`

type MarkPlanItemCompletedParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

// Logging implies the item is done; the log's own +10 XP comes next.
func (q *Queries) MarkPlanItemCompleted(ctx context.Context, arg MarkPlanItemCompletedParams) error {
	_, err := q.db.Exec(ctx, markPlanItemCompleted, arg.ID, arg.UserID)
	return err
}

const planItemToToggle = `-- name: PlanItemToToggle :one
SELECT i.item_type, i.title
FROM public.plan_items i
JOIN public.training_plans p ON p.id = i.plan_id
WHERE i.id = $1 AND p.user_id = $2
`

type PlanItemToToggleParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

type PlanItemToToggleRow struct {
	ItemType string `json:"item_type"`
	Title    string `json:"title"`
}

// The item's type and title (the log's note), owner only.
func (q *Queries) PlanItemToToggle(ctx context.Context, arg PlanItemToToggleParams) (PlanItemToToggleRow, error) {
	row := q.db.QueryRow(ctx, planItemToToggle, arg.ID, arg.UserID)
	var i PlanItemToToggleRow
	err := row.Scan(&i.ItemType, &i.Title)
	return i, err
}

const profileRole = `-- name: ProfileRole :one
SELECT COALESCE(role, 'student')::text AS role FROM public.profiles WHERE id = $1
`

func (q *Queries) ProfileRole(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, profileRole, id)
	var role string
	err := row.Scan(&role)
	return role, err
}

const saveSessionFeedback = `-- name: SaveSessionFeedback :exec
UPDATE public.session_logs SET ai_feedback = $1::jsonb
WHERE id = $2 AND user_id = $3
`

type SaveSessionFeedbackParams struct {
	Feedback []byte    `json:"feedback"`
	ID       uuid.UUID `json:"id"`
	UserID   uuid.UUID `json:"user_id"`
}

func (q *Queries) SaveSessionFeedback(ctx context.Context, arg SaveSessionFeedbackParams) error {
	_, err := q.db.Exec(ctx, saveSessionFeedback, arg.Feedback, arg.ID, arg.UserID)
	return err
}

const setPlanItemCompletion = `-- name: SetPlanItemCompletion :exec
UPDATE public.plan_items SET is_completed = $1 WHERE id = $2
`

type SetPlanItemCompletionParams struct {
	Completed bool      `json:"completed"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) SetPlanItemCompletion(ctx context.Context, arg SetPlanItemCompletionParams) error {
	_, err := q.db.Exec(ctx, setPlanItemCompletion, arg.Completed, arg.ID)
	return err
}
