// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: training.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const completePlanItem = `-- name: CompletePlanItem :one
SELECT public.complete_plan_item($1, $2, CAST($3::text AS date))::text AS result
`

type CompletePlanItemParams struct {
	ItemID    uuid.UUID `json:"item_id"`
	Completed bool      `json:"completed"`
	OnDate    string    `json:"on_date"`
}

// Step A (ADR-5): the SQL function toggles the item, writes/removes the
// linked log, and awards or compensates XP idempotently.
func (q *Queries) CompletePlanItem(ctx context.Context, arg CompletePlanItemParams) (string, error) {
	row := q.db.QueryRow(ctx, completePlanItem, arg.ItemID, arg.Completed, arg.OnDate)
	var result string
	err := row.Scan(&result)
	return result, err
}

const getPlanItemRef = `-- name: GetPlanItemRef :one

SELECT i.item_type, i.week, i.day_of_week, i.is_completed, p.created_at AS plan_created_at
FROM public.plan_items i
JOIN public.training_plans p ON p.id = i.plan_id
WHERE i.id = $1 AND p.user_id = $2
`

type GetPlanItemRefParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

type GetPlanItemRefRow struct {
	ItemType      string    `json:"item_type"`
	Week          int32     `json:"week"`
	DayOfWeek     int16     `json:"day_of_week"`
	IsCompleted   bool      `json:"is_completed"`
	PlanCreatedAt time.Time `json:"plan_created_at"`
}

// Training plans: plan-item completion (more arrives with the Training module).
// The item plus its plan's start, for the log-window check. Owner only.
func (q *Queries) GetPlanItemRef(ctx context.Context, arg GetPlanItemRefParams) (GetPlanItemRefRow, error) {
	row := q.db.QueryRow(ctx, getPlanItemRef, arg.ID, arg.UserID)
	var i GetPlanItemRefRow
	err := row.Scan(
		&i.ItemType,
		&i.Week,
		&i.DayOfWeek,
		&i.IsCompleted,
		&i.PlanCreatedAt,
	)
	return i, err
}
