package training

import (
	"context"
	"fmt"
	"strings"
	"time"

	"github.com/google/uuid"

	"github.com/hamid-karimi/coachin/apps/api/internal/app/apperr"
	"github.com/hamid-karimi/coachin/apps/api/internal/domain/dates"
	"github.com/hamid-karimi/coachin/apps/api/internal/domain/ics"
	"github.com/hamid-karimi/coachin/apps/api/internal/domain/planitem"
)

// ProgramRow is a stored active plan.
type ProgramRow struct {
	ID             uuid.UUID
	RaceDate       *string // YYYY-MM-DD
	GoalTime       *string
	WeeksTotal     int
	CreatedAt      time.Time
	PlanKind       string // race | hypertrophy
	RaceTarget     *string
	RaceDistanceKm *float64
	CreatedBy      *uuid.UUID
}

// Program is an active plan as the programs page shows it.
type Program struct {
	ProgramRow
	CurrentWeek   int  // 1..WeeksTotal
	DaysUntilRace *int // race plans only
	// FromCoach: generated by the trainee's coach (creator ≠ owner).
	FromCoach bool
	// ReviewWeek is the last fully elapsed week (0 during week 1).
	ReviewWeek int
	// CheckinDue: ReviewWeek has a next week to adjust and no check-in yet.
	CheckinDue bool
}

// ExportItem is a plan item for the calendar export.
type ExportItem struct {
	ID            uuid.UUID
	Week          int
	DayOfWeek     int
	ItemType      string
	Title         string
	Description   *string
	Details       planitem.Details
	PlanCreatedAt time.Time
}

// ProgramStore is the persistence the program use cases need.
type ProgramStore interface {
	ActivePrograms(ctx context.Context, userID uuid.UUID) ([]ProgramRow, error)
	// ReviewedWeeks returns, per plan, the weeks that already have a check-in.
	ReviewedWeeks(ctx context.Context, userID uuid.UUID, planIDs []uuid.UUID) (map[uuid.UUID]map[int]bool, error)
	ArchivePlan(ctx context.Context, userID, planID uuid.UUID) error
	ActivePlanItems(ctx context.Context, userID uuid.UUID) ([]ExportItem, error)
}

// Programs runs the program-manager use cases. now is injectable for tests.
type Programs struct {
	store ProgramStore
	now   func() time.Time
}

// NewPrograms builds the service; now defaults to time.Now.
func NewPrograms(store ProgramStore, now func() time.Time) *Programs {
	if now == nil {
		now = time.Now
	}
	return &Programs{store: store, now: now}
}

// List returns the user's active plans with week, race countdown, and
// check-in state.
func (p *Programs) List(ctx context.Context, userID uuid.UUID) ([]Program, error) {
	rows, err := p.store.ActivePrograms(ctx, userID)
	if err != nil {
		return nil, fmt.Errorf("load plans: %w", err)
	}
	now := p.now()
	programs := make([]Program, len(rows))
	var candidates []uuid.UUID
	for i, row := range rows {
		program := Program{
			ProgramRow:  row,
			CurrentWeek: dates.PlanWeekOf(row.CreatedAt, row.WeeksTotal, now),
			FromCoach:   row.CreatedBy != nil && *row.CreatedBy != userID,
			ReviewWeek:  dates.LastElapsedPlanWeek(row.CreatedAt, row.WeeksTotal, now),
		}
		if row.RaceDate != nil {
			if days, ok := dates.DaysUntil(*row.RaceDate, now); ok {
				program.DaysUntilRace = &days
			}
		}
		if program.ReviewWeek >= 1 && program.ReviewWeek < row.WeeksTotal {
			candidates = append(candidates, row.ID)
		}
		programs[i] = program
	}
	if len(candidates) == 0 {
		return programs, nil
	}
	reviewed, err := p.store.ReviewedWeeks(ctx, userID, candidates)
	if err != nil {
		return nil, fmt.Errorf("load check-ins: %w", err)
	}
	for i := range programs {
		pr := &programs[i]
		pr.CheckinDue = pr.ReviewWeek >= 1 && pr.ReviewWeek < pr.WeeksTotal && !reviewed[pr.ID][pr.ReviewWeek]
	}
	return programs, nil
}

// Archive retires an active plan; progress is kept. Archiving again, or a
// plan that is not the user's, changes nothing.
func (p *Programs) Archive(ctx context.Context, userID, planID uuid.UUID) error {
	return p.store.ArchivePlan(ctx, userID, planID)
}

// errNoActivePlan is returned as a 404 by the export.
var errNoActivePlan = apperr.New(apperr.NotFound, "No active plan")

// CalendarExport renders every active plan's sessions (meal notes excluded)
// as an .ics calendar of all-day events.
func (p *Programs) CalendarExport(ctx context.Context, userID uuid.UUID) (string, error) {
	items, err := p.store.ActivePlanItems(ctx, userID)
	if err != nil {
		return "", fmt.Errorf("load plan items: %w", err)
	}
	if len(items) == 0 {
		plans, err := p.store.ActivePrograms(ctx, userID)
		if err != nil {
			return "", fmt.Errorf("load plans: %w", err)
		}
		if len(plans) == 0 {
			return "", errNoActivePlan
		}
	}
	events := make([]ics.Event, 0, len(items))
	for _, item := range items {
		if !planitem.Checkable(item.ItemType) {
			continue // meal notes are not calendar events
		}
		events = append(events, ics.Event{
			UID:         item.ID.String() + "@coachin",
			Date:        dates.PlanItemDate(item.PlanCreatedAt, item.Week, item.DayOfWeek),
			Summary:     item.Title,
			Description: exportDescription(item),
		})
	}
	return ics.Calendar(events, p.now()), nil
}

func exportDescription(item ExportItem) string {
	var parts []string
	add := func(s string) {
		if s != "" {
			parts = append(parts, s)
		}
	}
	add(planitem.DetailLine(item.Details))
	if item.Description != nil {
		add(*item.Description)
	}
	if item.Details.Notes != nil {
		add(*item.Details.Notes)
	}
	if url := planitem.VideoURL(item.Details); url != "" {
		add("Form video: " + url)
	}
	return strings.Join(parts, "\n")
}
